### ISSUE TITLE
Add authentication for debug stack WebSocket API

### ISSUE THREAD

**Issue by fwang** [serverless-stack/sst#1409]
Need to figure out which authentication method should be used.

---
Requests
- Lawrence https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1643279859216000

**Comment by fezproof** [comment]
Hi @fwang, is there any more information regarding this issue? I cannot access the Slack link

**Comment by fezproof** [comment]
Also, does this mean the web socket connection to SST in debug mode completely unprotected? If so this entire framework is a non starter for a lot of teams and should probably be documented. Happy to be corrected if I misunderstand though :)

**Comment by fwang** [comment]
Hey @fezproof, we are moving away from debug stack in SST v2. In v2, SST will use the websocket server that already exist in your AWS IoT service instead. And that is protected by IAM permissions.

We will share a release candidate for v2 later this month.

**Comment by fezproof** [comment]
Awesome to hear, I saw the launch and what you guys are doing is pretty sweet!

**Comment by thdxr** [comment]
debug stack is gone in v2
