### ISSUE TITLE
Expand use case for `sst-env`

### ISSUE THREAD

**Issue by fwang** [serverless-stack/sst#1495]
### Use cases
1. StaticSite environment: sst start => sst-env -- npm run start **(supported)**
2. StaticSite environment: sst deploy => sst-env -- npm run start **(supported)**
3. Other values: run tests: sst-env -- jest **(requested)**
4. Other values: run scripts: sst-env -- my-script **(requested)**

### Proposed solutions
1. Allow adding other values to `static-site-environment-output-values.json`
  - ie. `this.addEnvironmentOutputs(id, { API_URL });`
  - pro: `sst-env` only depends on the `output-values.json` file
  - con: need to run `sst start/deploy` to generate the file before using `sst-env`
2. Fetch from SSM
  - ie. `new sst.Parameter(this, id, API_URL);` creates an SSM parameter `/sst/$app/$stage/$id`
  - ie. `sst-env --stage dev` loads all SSM parameters `/sst/$app/$stage/*` and sets them as environment variables
  - pro: not required to run `sst start/deploy`
  - con: does not handle use case 1 and 2, maybe make this a separate command `sst-run`?
  - con: requires IAM credentials to run `sst-env` (not a deal breaker)

### Other considerations
- Can we remove generating the `static-site-environment-output-values.json` file if we went with solution 2?
- If we went with solution 2, should we set the parameters as environment variables? Or let ppl access them manually using the `config` package?
- Is there still a need for `--output-file`? Or should Parameter values be written to the outputs file?

**Comment by dangreaves** [comment]
This would be very convenient for containers. I'm running a SvelteKit app inside a Fargate ECS container. I'm using the Fargate CDK construct do to this, which accepts environment variables.

When running the SvelteKit app locally, it would be great to have access to these environment variables using the `sst-env` utility. At the moment, I need to define them manually using a `.env.local` file, which is tedious.

This may be solved by adding Resource Binding support to Fargate containers (#2106), as that seems to be the newer way to be passing configuration and secrets.

**Comment by fwang** [comment]
Hey @dangreaves, side note, we officially released the [`SvelteKitSite`](https://docs.sst.dev/constructs/SvelteKitSite) construct. It's deployed to CloudFront/S3/Lambda.

Get started here — https://docs.sst.dev/start/svelte

**Comment by fwang** [comment]
Closing the issue as `sst env` has been renamed to `sst bind`.
