### ISSUE TITLE
The sst.json file is not validated

### ISSUE THREAD

**Issue by octogonz** [serverless-stack/sst#1585]
If I misspell a field name (e.g. `"esbuildconfig": "broken"`), the mistake is silently ignored by the SST CLI.  This seems  error-prone.

## Suggested fix

1. Publish a strict [JSON schema](https://json-schema.org/) describing the `sst.json` file format.  
2. If we put a `"$schema"` URL in the sample `sst.json` files, then developers would also get nice VS Code tips and error-underlining when editing this file.
3. The config file loader should validate the JSON against this schema (e.g. using [ajv](https://www.npmjs.com/package/ajv)).  I would also suggest that the loader should allow `//` comments for better JSON readability.

**Comment by octogonz** [comment]
(Originally I thought this file was undocumented, however I found descriptions of the settings in [installation.md](https://docs.serverless-stack.com/installation#project-config).)

**Comment by thdxr** [comment]
v2 uses a .mjs for config
