### ISSUE TITLE
Add remix.run support

### ISSUE THREAD

**Issue by lefnire** [serverless-stack/sst#1635]
Not sure how hard it'd be post 1.0 to add Remix support. Could give SST a good adoption boost, since Remix is talk of the town these days. I know SST-Next uses SLS-Next under the hood, maybe could do the same via [this SLS component](https://github.com/shamsup/remix-starter-serverless). Alternatively reference Remix's [lean on Architect](https://github.com/remix-run/remix/tree/main/templates/arc) for AWS deployment.

Low prio of course, just adding since I didn't see a ticket yet.

**Comment by simonireilly** [comment]
It's fairly easy to remove the architect dependency.

Here's it rewriten in aws-cdk for you.

Putting this into serverless stack will be very straightforward

https://github.com/simonireilly/funk-stack

Serverless stack could watch and recompile this lambda locally in about 400ms I suspect.

The local assets can be S3 synced very quickly, I suspect.

The example I have here already runs with cdk watch, but recompile is about 10 seconds which is not ideal

**Comment by fwang** [comment]
Keeping track a list of requests from the Slack community:
- Karolis https://serverless-stack.slack.com/archives/C01JG3B20RY/p1651231063259209

**Comment by fwang** [comment]
Remix released earlier in July https://docs.sst.dev/constructs/RemixSite
