### ISSUE TITLE
Errors synthesizing are not exposed when re-deploying in `sst start`

### ISSUE THREAD

**Issue by andres-sm** [serverless-stack/sst#1640]
When running in "Dev" mode, if you have validation or other errors during the synthesizing step they are printed to the console, instead the deploy looks "stuck" and doesn't make any forward progress.

The output log looks like this

```
$ npm run start

...

Stacks: Building changes...
Stacks: Synthesizing changes...
```

The error only becomes apparent if you Ctr+C out of the dev mode, and try to run `npm run start` again. Then an error is printed correctly.

```
Error: Validation failed with the following errors:
```

**Comment by thdxr** [comment]
Fixed in v2
