### ISSUE TITLE
Transient dependencies unsafely used in `.build/run.js`

### ISSUE THREAD

**Issue by mmkal** [serverless-stack/sst#1656]
Hi there! I'm using sst on a [rush](https://rushjs.io) project and noticed a problem in the way the `.build/run.js` file is generated. I haven't fully gone through this file to figure out what it's doing exactly, but the basic problem is that it uses peer dependencies of `@serverless-stack/cli` that the user doesn't necessarily have. The example I hit were `source-map-support`, `fs-extra`, `chalk`, `@serverless-stack/resources`, but conceivably there could be others that I happened to have installed already.

Anyone using rush/pnpm is almost guaranteed to hit this (I guess #854 is relevant) - but it's also a bug for any package manager, it's just less likely to surface with the npm/yarn installation systems, and yarn/lerna hoisting.

pnpm uses hard links so that `chalk`, to use one of the examples above, lives under `user-project-directory/@serverless-stack/cli/node_modules/chalk`, rather than `user-project-directory/node_modules/chalk`, where it will usually live with npm/yarn.

But even with npm and yarn, you're really just relying on luck - if the user has an incompatible, different version of `chalk`, `.build/run.js` will load the user's one, rather than the one that's been developed against and tested in this repo.

In fact with chalk, the latest/default version is 5.0.1, but `sst` is only compatible with 4.1.0, so this is not even a hypothetical scenario - you might well get npm/yarn users who use a newer version of chalk hitting problems very soon.

One fairly simple solution would be to expose some passthrough modules like a `deps.ts` file which is something like:

```ts
export * as chalk from 'chalk'
export * as fs from 'fs-extra'
export * as sstCore from '@serverless-stack/core'
```

Then update `.build/run.js` to import from that module instead of from the external dependencies (`import {chalk, fs, sstCore} from '@serverless-stack/cli/deps'` or something)

**Comment by fwang** [comment]
Got it! Thanks for the thorough breakdown of the issue.

@thdxr recently looked at the packager side of things, I will let him comment.

**Comment by kamsar** [comment]
This issue also seems to affect my pnpm 7.1 setup without rush fwiw

**Comment by cefn** [comment]
I was similarly affected. To create a new pnpm module within my monorepo for a serverless stack, I needed to install `fs-extra` `chalk` and `@serverless-stack/core` which were undeclared dependencies of `.build/run.mjs` which I did not already have installed globally.

**Comment by thdxr** [comment]
We're planning on getting rid of `run.mjs` soon so this should not be an issue

**Comment by ErikMikkelson** [comment]
When is this work going to be done?  This is still an issue

**Comment by thdxr** [comment]
This is eliminated in v2
