### ISSUE TITLE
Confusing Authorizer Docs and Examples

### ISSUE THREAD

**Issue by AshHeskes** [serverless-stack/sst#1675]
Looking through the examples on adding an Auth0 Authorizer to my API routes. It seems the Examples are either out of date or incorrect.

In the downloaded example (api-auth-jwt-auth0) the code reads as: 

```javascript
const api = new Api(stack, "Api", {
    authorizers: {
      jwt: {
        type: "jwt",
        cdk: {
          authorizer: new apigAuthorizers.HttpJwtAuthorizer(
            "Authorizer",
            "https://sst-test.us.auth0.com/",
            {
              jwtAudience: ["r7MQkwTZjIzcKhGmlcy9QhMNXnT9qhwX"],
            }
          ),
        },
      },
    },
    defaults: {
      authorizer: "jwt",
    },
    routes: {
      "GET /private": "private.main",
      "GET /public": {
        function: "public.main",
        authorizer: "jwt",
      },
    },
  });
```

In the docs for the example it reads as (https://serverless-stack.com/examples/how-to-add-jwt-authorization-with-auth0-to-a-serverless-api.html):

```javascript
// Create Api
    const api = new sst.Api(this, "Api", {
      defaultAuthorizer: new apigAuthorizers.HttpJwtAuthorizer(
        "Authorizer",
        "https://myorg.us.auth0.com/",
        {
          jwtAudience: ["UsGRQJJz5sDfPQDs6bhQ9Oc3hNISuVif"],
        }
      ),
      defaultAuthorizationType: sst.ApiAuthorizationType.JWT,
      routes: {
        "GET /private": "src/private.main",
        "GET /public": {
          function: "src/public.main",
          authorizationType: sst.ApiAuthorizationType.NONE,
        },
      },
    });
``` 

The docs seem clearly out of date in regards to class signature. But not only that. In the raw documentation you use a an inbuilt construct for jwt auth (with auth0 props https://docs.serverless-stack.com/constructs/Api#adding-jwt-authorization).

```javascript
new Api(stack, "Api", {
  authorizers: {
    myAuthorizer: {
      type: "jwt",
      jwt: {
        issuer: "https://myorg.us.auth0.com",
        audience: ["UsGRQJJz5sDfPQDs6bhQ9Oc3hNISuVif"],
      }
    },
  },
  routes: {
    "GET /public": "src/public.main",
    "GET /private": {
      authorizer: "myAuthorizer",
      function: "src/private.main",
    },
  },
});
```

You also provide a userpool JWT example in the raw docs using Auth0. Which doesn't make sense since I don't see how cognito user pools and Auth0 are related (https://docs.serverless-stack.com/constructs/Api#apijwtauthorizer)

```javascript
new Api(stack, "Api", {
  authorizers: {
    Authorizer: {
      type: "jwt",
      userPool: {
        issuer: "https://abc.us.auth0.com",
        audience: ["123"],
      },
    },
  },
});
```

Then referring back to the auth0 example docs (https://serverless-stack.com/examples/how-to-add-jwt-authorization-with-auth0-to-a-serverless-api.html). There's an AWS CDK construct being used for the auth0 JWT authoriser. It's not clear how this differs from the (apparently recent) inbuilt JWT authorizer. Which might not be a problem if only your documentation simply says this about using the CDK method (https://docs.serverless-stack.com/constructs/Api#cdkauthorizer)

 ```text
 cdk.authorizer
Type : [HttpLambdaAuthorizer](https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-apigatewayv2-authorizers-alpha.HttpLambdaAuthorizer.html)

This allows you to override the default settings this construct uses internally to create the authorizer.
```

But there's no documentation on how these defaults might differ from your inbuilt JWT authorizer. 

To make matters even more confusing (although not your fault) is the AWS documentation on it (https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-apigatewayv2-authorizers-alpha.HttpJwtAuthorizer.html). 

```txt
Authorize Http Api routes on whether the requester is registered as part of an AWS Cognito user pool.
```

Which kind of tells me this JWT authorizer is for cognito user pools. Which for Auth0 it wouldn't be, so why is this method used in the example docs (https://serverless-stack.com/examples/how-to-add-jwt-authorization-with-auth0-to-a-serverless-api.html)

FYI I haven't actually ran any of the code to try and figure out the different behaviour. Since I was just left confused.

**Comment by AshHeskes** [comment]
Which is the correct and simplest method to use SST with Auth0 when you simply want to use Auth0 for username+password and social login?

**Comment by Manitej66** [comment]
Hi @AshHeskes ,
The examples were updated, please check now.

**Comment by AshHeskes** [comment]
Sorry for taking a while to get back to this. I hadn't realised that the AWS JWT authoriser is really only useful for JWKS OpenID setups. I assumed it was quite universal and thus allowed me to supply a signing secret/key for more basic JWT token authorisations.

It might be worth mentioning that in the docs. 

In any event I have moved away from Auth0 at this in favour of handling Auth myself. Thanks for your help.
