### ISSUE TITLE
Speed up "syncing metadata" process

### ISSUE THREAD

**Issue by fwang** [serverless-stack/sst#1733]
The more CFN stacks you have in your AWS account, the longer the "syncing metadata" step takes.

It loads in 2min for Robert.

---
Requests:
- Robert https://serverless-stack.slack.com/archives/C01JG3B20RY/p1653411476070049?thread_ts=1652984695.020809&cid=C01JG3B20RY

**Comment by thdxr** [comment]
This was fixed when we added the metadata to s3
