### ISSUE TITLE
Cron stack pass environment variables

### ISSUE THREAD

**Issue by PJCAfonso** [serverless-stack/sst#1779]
How to pass environment variable when define a cron stack?

We tried this code

```
export default class ApiStack extends sst.Stack {
    cron; 
    constructor(scope, id, props) {
        super(scope, id, props);

        const stage = this.node.root.stage;
        const { myTable } = props;

        this.cron = new sst.Cron(this, "Cron", {
            schedule: "rate(2 minutes)",
            job: "src/mycode.main",
            defaultFunctionProps: {
                environment: {
                    MYNAME_TABLE_NAME: myTable.tableName,
                }
            }
        }
        this.cron.attachPermissions([myTable]);
   }
}
```

But when I tried to use that variable to constructor a params to do a DynamoDB call, that variavle is undefined.

the content of mycode.js file.
`
export async function main() {
    console.log("props cron", process.env.MYNAME_TABLE_NAME);
}
`

What are the correct way to pass MYNAME_TABLE_NAME value to my functions?

Thanks in advance

**Comment by jannylund** [comment]
I just tried to do the same thing. A bit of digging in code and I ended up with this working solution.

```
    const cron = new Cron(stack, "Cron", {
        schedule: "rate(1 minute)",
        job: {
            function: {
                permissions: [table],
                environment: {
                    TABLE_NAME: table.tableName,
                },
                handler: "main.handler"
            }
        }
    });

```

**Comment by PJCAfonso** [comment]
> function: {
>                 permissions: [table],
>                 environment: {
>                     TABLE_NAME: table.tableName,
>                 },
>                 handler: "main.handler"
>             }

Thanks, but not working yet. Which version you are using.
Mine is 0.69.6.

With major update and upgrades, I affraid with problems doing update/upgrade in our production app.

**Comment by jannylund** [comment]
@PJCAfonso I'm on 1.1.1, so probably some different internals there.

**Comment by fwang** [comment]
@PJCAfonso the snippet @jannylund shared should also work in v0.69.6. Try this:
```js
export default class ApiStack extends sst.Stack {
    cron; 
    constructor(scope, id, props) {
        super(scope, id, props);

        const stage = this.node.root.stage;
        const { myTable } = props;

        this.cron = new sst.Cron(this, "Cron", {
            schedule: "rate(2 minutes)",
            job: {
              function: {
                handler: "src/mycode.main",
                environment: {
                    MYNAME_TABLE_NAME: myTable.tableName,
                }
            }
        }
        this.cron.attachPermissions([myTable]);
   }
}
```

To check without deploying, you can run `sst build`, and check the generated CloudFormation template file in `.build/cdk.out`. Grep for `MYNAME_TABLE_NAME` and see if it's set in the function's environment prop.

Let me know if it works for you.

**Comment by PJCAfonso** [comment]
Solved with last help
