### ISSUE TITLE
Typo on migration documentation - Topic Subscriber

### ISSUE THREAD

**Issue by dwpdx** [serverless-stack/sst#1803]
This example list notifications in the "to" section, instead of subscribers. I am happy to submit a PR if needed.

// from
subscribers: [
  "src/subscriber1.main"
  "src/subscriber2.main"
]

// to
notifications: {
  "0": "src/subscriber1.main",
  "1": "src/subscriber2.main",
}

https://github.com/serverless-stack/serverless-stack/blob/master/www/docs/constructs/v0/migration.md

**Comment by fwang** [comment]
Fixed
