### ISSUE TITLE
/backend folder in the tutorial does not exist

### ISSUE THREAD

**Issue by mrpaulstone** [serverless-stack/sst#1823]
Brand new user here.

I tried to follow this guide exactly: https://serverless-stack.com/examples/how-to-create-a-reactjs-app-with-serverless.html

The /backend  folder was not created, have things changed and does the tutorial need fixing?

**Comment by auditt98** [comment]
The tutorial needs fixing, it's now called /api. Though i guess you can change the folder name to whichever you'd like and set srcPath in stacks/index.js to the new name.

**Comment by fwang** [comment]
Thanks for bringing it up!

Fixed.
