### ISSUE TITLE
Lambda Websocket Authorizer not working

### ISSUE THREAD

**Issue by niallel** [serverless-stack/sst#1866]
Hi,

There are two examples in the documentation for configuring a lambda authorizer for web sockets.

The first at https://docs.sst.dev/constructs/WebSocketApi#authorization

```ts
new WebSocketApi(stack, "Api", {
  authorizer: {
    type: "lambda",
    function: new Function(stack, "Authorizer", {
      handler: "test/lambda.handler",
    }),
  },
});
```

returns the error when building:
Type 'WebSocketApi' is missing the following properties from type 'Function': _isLiveDevEnabled, localId, createUrl, currentVersion, and 60 more.

The second at https://docs.sst.dev/constructs/WebSocketApi#authorizer 

```ts
new WebSocketApi(stack, "Api", {
  authorizer: {
    type: "lambda",
    function: new Function(this, "Authorizer", {
      handler: "src/authorizer.main",
    }),
  },
  routes: {
    $connect: "src/connect.main",
    $default: "src/default.main",
    $disconnect: "src/disconnect.main",
  },
});
```

doesn't get invoked, but the web socket connection is denied.

Is there a working example, documentation is wrong, there is a bug, or I'm being stupid and doing something wrong?

Many thanks,

**Comment by fwang** [comment]
Hi @niallel, sorry for super late response. Did you figure out what the issue was?

**Comment by niallel** [comment]
Sorry, didn’t find out a solution, then changed my code to use client side polling.On 12 Jan 2023, at 21:48, Frank ***@***.***> wrote:﻿
Hi @niallel, sorry for super late response. Did you figure out what the issue was?

**Comment by geauser** [comment]
@fwang I have the same issue, have you looked into it?

Here is my code:

```js
const api = new WebSocketApi(stack, 'ws', {
  authorizer: {
    type: 'lambda',
    identitySource: ['route.request.querystring.jwt'],
    function: new Function(stack, 'Authorizer', {
      handler: 'packages/functions/src/authorizer.handler',
    },
  },
  routes: {
    '$connect':    'packages/functions/src/ws/connect.handler',
    '$disconnect': 'packages/functions/src/ws/disconnect.handler',
    'sendMessage': 'packages/functions/src/ws/sendMessage.handler',
  }
});
```

The authorizer gets called, but returning `{ isAuthorized: true }` in it, does not let the request reach `connect.handler` for the connect event.

**Comment by fwang** [comment]
Following up here https://discord.com/channels/983865673656705025/1103635174568243210
