### ISSUE TITLE
Confusing Function props

### ISSUE THREAD

**Issue by trevorallred** [serverless-stack/sst#1867]
I incorrectly created a function using the following route definition:
```
'GET /url/path': {
  function: 'function/path',
  bundle: {
    copyFiles: [{ from: 'functions/pdf/data' }]
  }
}
```

However, the bundle props were totally ignored until I changed it to:
```
'GET /url/path': {
  handler: 'function/path',
  bundle: {
    copyFiles: [{ from: 'functions/pdf/data' }]
  }
}
```

I burned a lot of time stepping through the client code to figure out what was happening. Maybe the docs could be improved or better yet, the client code could warn if it's going to ignore all the properties. The line that finally clued me in was this one: https://github.com/serverless-stack/sst/blob/fb7d3b02a9026b31e42167473d7d3eba21a63f7a/packages/resources/src/Function.ts#L1066

My function was just a string rather than an object at this point.

**Comment by thdxr** [comment]
Fixed in v2
