### ISSUE TITLE
SST CLI does not use $AWS_CA_BUNDLE for SSL validation

### ISSUE THREAD

**Issue by HenrikStanley** [serverless-stack/sst#1902]
When working on systems behind corporate proxys or SSL inspection systems like ZScaler, traffic is inspected by a middleware tool.
For the AWS CLI, this is solved using the $AWS_CA_BUNDLE environment variable.

Using this variable we can point to a filepath of a cacert.pem file that has all the default AWS CAs stored, but also contains the CA for our SSL inspection service (in our case ZScaler). This allows the CLI to work even behind SSL inspection.

The second option is to rely on the operating systems CA store and use the allowed CAs in the system store to validate the request.

On my test bench I have both add the SSL inspection tool to the machine store and injected the certificate into the cacert.pem file.
This makes both AWS CDK and AWS CLI work.

However when I am trying to run `npx sst start` or `pnpm sst start`, I get the following error:
```shell
Using stage: demo
Preparing your SST app

=======================
 Deploying debug stack
=======================


Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1532:34)
    at TLSSocket.emit (node:events:527:28)
    at TLSSocket.emit (node:domain:475:12)
    at TLSSocket._finishInit (node:_tls_wrap:946:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:727:12)
```
This indicates to me that the SST CLI uses its own CAs and not the system ones or the ones used by the AWS CLI.
Is there any way to standardize this to respect the same way things are done in AWS CLI or provide documentation on how to adjust the SST CLI to work when you need to ensure that SSL requests respects the CA of a middleware SSL inspection?

**Comment by fwang** [comment]
Hey @HenrikStanley, to get CDK to work, did you have to set the $AWS_CA_BUNDLE environment or did you pass in the `--ca-bundle-path` cli option?

**Comment by HenrikStanley** [comment]
@fwang 

After a very very lengthy series of troubleshooting it seems like the issue stems from the recently added SSO implementation in CDK not working properly with the AWS_CA_BUNDLE parameter.

I have created an bug report for this on the CDK GH pages:
https://github.com/aws/aws-cdk/issues/21328
Since I am assuming this is the root cause spilling its way up to SST I will close this issue.

**Comment by fwang** [comment]
Got it. Btw does pinning SST to an older version work? (older SST versions are on older CDK versions).

Let me know if there's anything we can do on our side to get it going for u.
