### ISSUE TITLE
Bucket creation hangs on `Custom::S3AutoDeleteObjects` on newer versions of SST.

### ISSUE THREAD

**Issue by sam-sbl** [serverless-stack/sst#1909]
I have an app currently deploying correctly on version `1.2.16` of SST. I recently upgraded using `npx sst upgrade`, which bumped it to `1.6.1`, and the deploys hang while waiting for `Custom::S3AutoDeleteObjects` to deploy - it never does, and has to roll back. I'm not sure whether this is an underlying issue with CDK, as the version of that also shifted from `2.24.0` to `2.32.1`.

**Comment by bshrStowk4** [comment]
I have this problem too

**Comment by w5mix** [comment]
I ran into this, running 1.6.2

**Comment by w5mix** [comment]
Downgrading to 1.4.1 fixed this for me, which also happens to be the version right before the shift to CDK 2.32.  So, not sure if the issue with SST or CDK.  Additionally, I had to rename the stack to something else, because AWS won't allow me to delete the "Custom::S3AutoDeleteObjects" resource.

**Comment by fwang** [comment]
Thanks for bringing up it! @sam-sbl @bshrStowk4 @w5mix

Just released [v1.6.6](https://github.com/serverless-stack/sst/releases/tag/v1.6.6) with the fix. Can you give it a try?
