### ISSUE TITLE
Dry run CLI flag

### ISSUE THREAD

**Issue by AshHeskes** [serverless-stack/sst#1929]
Just a thought on a feature request. It would be great if the CLI had a flag that could be passed to say do a dry run. Which is to say run my stack code but don't actually attempt deploy anything anywhere. I think this can only be "truly" possible for stacks using purely SST constructs. However I think it's a useful feature for quick local development of complex stack related code and could further set you apart from what's available with CDK directly.

Thoughts?

**Comment by thdxr** [comment]
Does using `sst diff` help this situation? It basically synthesizes and shows you what would change

**Comment by AshHeskes** [comment]
@thdxr This seems to work well as a substitute thnks.
