### ISSUE TITLE
`Stack` construct should reference `root.account` rather than env var

### ISSUE THREAD

**Issue by mikestopcontinues** [serverless-stack/sst#1930]
You'll see on [this line](https://github.com/serverless-stack/sst/blob/645a5e3c1a61cbfdbf1f52bb1611976afa7262fd/packages/resources/src/Stack.ts#L52), account is being pulled from the wrong place. Discussed with @fwang

**Comment by fwang** [comment]
Release in v1.6.9

Thanks @mikestopcontinues
