### ISSUE TITLE
Unable to tag SST Bootstrap

### ISSUE THREAD

**Issue by RichiCoder1** [serverless-stack/sst#1964]
It looks like a new bootstrap specific to SST was added with 1.8. However, it's not clear to how to manually deploy or tag this stack so it's resulting in all deploys getting blocked in our environment since we enforce tagging.

**Comment by fwang** [comment]
Hey @RichiCoder1, just added the `sst bootstrap` command. U can manually bootstrap like this:
```bash
npx sst bootstrap --tags key1=value1 key2=value2
```

This will go out in the next release in a few hours.

**Comment by RichiCoder1** [comment]
@fwang awesome, thanks for hoppin' on this so quick!

**Comment by fwang** [comment]
@RichiCoder1 it's released in [v1.8.2](https://github.com/serverless-stack/sst/releases/tag/v1.8.2)

**Comment by RichiCoder1** [comment]
I'm afraid it's not entirely resolved 😅.

![image](https://user-images.githubusercontent.com/2391878/185761243-c68e0419-1157-4741-be8d-a72b7c59ebc4.png)

Looks like the tags are getting JSON encoded and passed to a subprocess, but it's failing likely due to some fun w/ quoting under PowerShell & Windows.

**Comment by fwang** [comment]
Hey @RichiCoder1 , figured it out. It's an issue with Windows specifically.

Fixed in v1.8.3

Let me know if it works for you.

**Comment by RichiCoder1** [comment]
@fwang that did it!
