### ISSUE TITLE
Config: ability to customize SSM prefix

### ISSUE THREAD

**Issue by fwang** [serverless-stack/sst#1983]
Tim mentioned:
> is it possible to change the pattern the config feature uses for parameter names? the project I'm working on has established naming patterns for things like this and `/sst/{appName}/{stageName}/parameters/{PARAM_NAME}` might not fly

> generally something like `/{company}/{division}/{account alias}/{vpc name}/{app name}/{free form from here}`
---
Requests:
- Tim https://discord.com/channels/983865673656705025/983865673656705028/1011018049257754654

**Comment by brinsleylogic** [comment]
We've used a similar mark up in the last few places I've worked:

`/company/stage/app name/parameter name`

**Comment by fwang** [comment]
Does it have to be: `/company/{stage}/{app}/{parameter}` or would this work `/company/{stage}/sst/{app}/{stage}/secrets/{parameter}`?

So essentially still following the company policy just by prefixing with `/company/{stage}`.

**Comment by brinsleylogic** [comment]
I think in Tim's position it'd be harder to change as it sounds like it's a company-wide standard. If we could set a marked up string somewhere that's gets processed with replacers you should be able to offer something that's completely customisable.

For the cases where most people would want this I'm assuming they're in our boat and need to be able to have their own, non-standardisable structure.

**Comment by brinsleylogic** [comment]
@fwang, I thought I'd have a quick play with this this evening but seem to be having some issues getting the repo up and running on my machine; however I did have a poke around the codebase and came up with this - think it needs further refinement though.

`core/function-config`
```ts
let _ssmSecretPrefix: string

export function setSsmSecretPrefix(value: string) {
  _ssmSecretPrefix = value
}

export function buildSsmPrefixForSecret(app: string, stage: string) {
  return !_ssmSecretPrefix
    ? `/sst/${app}/${stage}/secrets/`
    : _ssmSecretPrefix.replace(/\{stage\}/g, stage)
}
```

`resources/Secret`
```ts
  public static setSsmPrefix(value: string) {
    FunctionConfig.setSsmSecretPrefix(value)
  }
```

In the actual stack code:
```ts
Config.Secret.setSsmPrefix("/my-company/{app}/{stage}/secrets/")
new Config.Secret(stack, "my-secret")

// With stage=prod, app=my-app it should produce:
// /my-company/my-app/prod/secrets/my-secret
```

Probably a cleaner way to do this.

**Comment by kuba-gaj** [comment]
We also have a custom naming convention at our company that prevents us from using `Config`. I really wish we could use it 

We would need to be able to set a custom string with placeholders or even better have a method that would return a full SSM path for both normal and fallback params (as ideally, we would also do some case transformation from `ENV_VARS` to `ssm-vars`).

If you agree I could have a go at implementing it and submitting PR.

**Comment by fwang** [comment]
Added support for customizing SSM name prefix in v1.16.1. Here's an example — https://docs.sst.dev/advanced/customizing-ssm-parameters
