### ISSUE TITLE
fetch is not a function

### ISSUE THREAD

**Issue by skystash** [serverless-stack/sst#1999]
Running `npx create-sst@latest my-app` (v1.9.1) throws this error after choosing a template.

**Comment by kevinvu184** [comment]
Get the same error in v1.9.2 - `SyntaxError: The requested module 'node-fetch' does not provide an export named 'fetch'`

A temporary fix:
1. Run create sst in 1.9.0: `npx create-sst@1.9.0 my-app`
2. `cd my-app`
3. `npm install`
4. Then, update to the latest (v1.9.2) `npx sst update v1.9.2`

**Comment by thdxr** [comment]
This is fixed in 1.9.3
