### ISSUE TITLE
Remix-site malformed cookie in request header when using regional server

### ISSUE THREAD

**Issue by lwsn** [serverless-stack/sst#2020]
When building request headers for the remix handler, cookies are appended twice. Once when mapping through `event.headers`, where Cookie is a prop, and once using `event.cookies`. This results in a comma as a separator in the middle of an otherwise semi-colon separated string.

Example result: `key1=value1; key2=value2, key1=value1; key2=value2`.

This causes parsing issues, eg: `key=value, key=value`, which gets parsed as `{ key: "value, key=value"}`.

Relevant lines:
https://github.com/serverless-stack/sst/blob/9da24d49cebf2a166e3b947188de10767e8f03d1/packages/resources/assets/RemixSite/server-lambda/regional-server.js#L106
https://github.com/serverless-stack/sst/blob/9da24d49cebf2a166e3b947188de10767e8f03d1/packages/resources/assets/RemixSite/server-lambda/regional-server.js#L111
https://github.com/serverless-stack/sst/blob/9da24d49cebf2a166e3b947188de10767e8f03d1/packages/resources/assets/RemixSite/server-lambda/regional-server.js#L116

**Comment by w5mix** [comment]
We have experienced this first hand as well.

**Comment by fwang** [comment]
Sorry about the delay! Released in v1.12.2
