### ISSUE TITLE
v1.11.0 broke lambdas

### ISSUE THREAD

**Issue by kuba-gaj** [serverless-stack/sst#2032]
We noticed that after upgrading to v1.11.0:
- local function development is broken with `Runtime.HandlerNotFound`
- all deployed functions are broken with `index.js` content of 
```
export function placeholder() {}
```
- node runtime is hardcoded to `nodejs16.x` even though we set `nodejs14.x` with `app.setDefaultFunctionProps`

**Comment by fwang** [comment]
Fixed in v1.12.4
