### ISSUE TITLE
Deploy via GitLab stopped working after v1.10.6

### ISSUE THREAD

**Issue by b4hr4m** [serverless-stack/sst#2053]
`npx sst deploy --stage prod ` works fine locally with the latest version.
Tried to deploy via GitLab. I got this error:

`Error: Subprocess exited with error 13
    at ChildProcess.<anonymous> (/builds/the-nick-wilson/todoist-time-sector-helper/node_modules/aws-cdk/lib/api/cxapp/exec.ts:131:23)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
There was an error synthesizing your app.`

I spent several hours to find a solution. 
Found this thread: https://discord.com/channels/983865673656705025/1017189364578664468/1017429633475543131
Seems "Parallel Building" cause this issue. Downgrading to v1.10.6 solved the problem.

**Comment by vectorhacker** [comment]
We've been affected by this issue. I'm one of the guys in that thread. We can't downgrade to v1.10.6 because we need the stack metadata fix. Is there a way to disable parallel building?

**Comment by fwang** [comment]
@vectorhacker @b4hr4m how many lambda functions do u have in ur app? And does it work when building locally?

**Comment by b4hr4m** [comment]
I used the NextjsSite construct and haven't added any lambda functions to my stack. Build and deploy works just fine locally.

**Comment by b4hr4m** [comment]
Fixed in v1.12.4
