### ISSUE TITLE
Python Runtime mistaken for nodejs when using external layer

### ISSUE THREAD

**Issue by myblackbeard** [serverless-stack/sst#2059]
I want to deploy a lambda function that uses an external layer like so: 

```typescript
const layer = aws_lambda.LayerVersion.fromLayerVersionArn(stack, "Layer", "arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p39-pandas:7");
```

Then I want to create the lambda here: 

```typescript
const lambda = new Function(stack, "my_lambda", {
        bundle: {
                  installCommands: [
                    "pipenv requirements > requirements.txt",
                    "pip install -r requirements.txt -t .",
                  ],
                },
        runtime: "python3.9",
        handler: "my_lambda.lambda_handler",
        srcPath: "path_to_my_lambda",
        layers: [layer],
    });
```

When I want to deploy this function I get the following error: 
`Error: This lambda function uses a runtime that is incompatible with this layer (nodejs16.x is not in [python3.9])`

So somehow it is assumed that the layer is for nodejs? 
When I leave out the layers parameter in the `Function`, then I can see the layer and lambda both being created successfully, both with Python version 3.9. 

What can I do here?

**Comment by fwang** [comment]
Hey @myblackbeard, can you try this workaround:
```ts
// change
layers: [layer],
// to
layers: app.local ? [] : [layer],
```

When running `sst start`, a fake/stub lambda is deployed in `nodejs` runtime, so it's incompatible w/ the layer.

Let me know if the workaround works, I will put in a proper fix.

**Comment by myblackbeard** [comment]
Hi @fwang, 

thanks a lot for the super quick reply! 
I'm defining the layers and lambdas in the context of a stack, so there's no `app` for me to reference and an error is thrown if I move it to the app scope, saying I shouldn't do that. 
Is there an alternative solution in the stack scope?
I guess I misinterpreted something - sorry, first day of SST usage!

**Comment by myblackbeard** [comment]
Thanks a lot for the quick reply, got it to work now by creating the layer locally and referring to that there. Then I initially still got the same issue, but when I stopped defining the `compatibleRuntimes` parameter completely it started to work!

**Comment by fwang** [comment]
Glad u figured it out.. you can access `app` in ur Stack file like this:
```ts
export function MyStack({ app, stack }) {
  ...
}
```
And if u r using typescript:
```ts
export function MyStack({ app, stack }: StackContext) {
  ...
}
```

**Comment by fwang** [comment]
Hey @myblackbeard, just added a fix for this in v1.14.3, no need to drop the `compatibleRuntimes` for the layer.

**Comment by myblackbeard** [comment]
Fantastic!!! Thanks a lot!

**Comment by vs-solution7** [comment]
@fwang I am still getting the error message when I set compatibleRuntimes

```
const myLayer = new lambda.LayerVersion(stack, 'myLayer', {
        code: lambda.Code.fromAsset('layers/my_layer'),
        compatibleRuntimes: [Runtime.PYTHON_3_11],
    });


function myFunction =  new Function(stack, "my-function", {
            runtime: 'python3.11',
            layers: [
              myLayer 
            ],
            memorySize: 512,
            handler: "packages/my_function",
            architecture: 'x86_64',
            timeout: 10,
            bind: [myBucket],
        });
```


Error message
```
Error: This lambda function uses a runtime that is incompatible with this layer (nodejs18.x is not in [python3.11])
```

Should I get rid of compatibleRuntimes in Layer and does it work? If I remove it, deployment is success, but layers are broken.

**Comment by joaocanaverde-blue** [comment]
@fwang I have a similar issue when adding a lambda function with `runtime: 'python3.11'` to `datadog-cdk-constructs-v2/Datadog`. It's detected as a NodeJS runtime, even though it's Python.

```
Resource myFunctionName has a Node.js runtime, but no Node.js Lambda Library version was provided. Please add the 'nodeLayerVersion' parameter for the Datadog serverless macro.
```

Using SST `2.43.4` (latest as of 13 August 2024), running `sst deploy`.

Any ideas?  🙂

**Comment by joaocanaverde-blue** [comment]
@fwang still happening with 2.43.6 - any ideas?
