### ISSUE TITLE
StaticSite construct with Gatsby is not working

### ISSUE THREAD

**Issue by m4tty-d** [serverless-stack/sst#2108]
Hey guys,

We are trying to deploy an existing Gatsby site with SST.

We followed the [official documentation](https://sst.dev/examples/how-to-create-a-gatsbyjs-app-with-serverless.html), but we keep getting the following error in the console while running `sst deploy` (it works with `sst start`):

`CREATE_FAILED | Custom::SSTBucketDeployment | GatsbySiteS3Deployment3308F5E2 | Received response status [FAILED] from custom resource. Message returned: invalid request. Missing key 'Status' (RequestId: 76aeb67a-fa61-443f-8cb5-7aead56c8276)`

After opening CloudWatch, there's a more descriptive error message: 

<img width="2213" alt="image" src="https://user-images.githubusercontent.com/6316925/193025775-d0e78d78-3c76-40cb-8b2b-0882b2c26161.png">

The error is easily reproducible with the [official gatsby example](https://github.com/serverless-stack/sst/tree/master/examples/gatsby-app) too.

There was an [ongoing discussion about this on Discord](https://discord.com/channels/983865673656705025/1016825800634417243), but no solution was found there.

However, we've noticed that the error only occurs if we pass in an environmental variable to the StaticSite construct, which is getting its value from another construct. (Api construct in our case -> GATSBY_APP_API_URL: api.url)

**Comment by fwang** [comment]
Fixed in v1.15.5
