### ISSUE TITLE
Add support for adding cognito SAML federated provider

### ISSUE THREAD

**Issue by Euclidean-Dev** [serverless-stack/sst#2114]
Aws-cdk v2.39.1 doesn't support declaring a cognito SAML provider.  It was added in version 2.42.  Any chance the cdk dependency to can be updated to .42 or latest? 

https://github.com/aws/aws-cdk/releases/tag/v2.42.0

**Comment by Switchur** [comment]
We've the same issue.

**Comment by fwang** [comment]
@Euclidean-Dev @Switchur Got it! Will update this week.

**Comment by fwang** [comment]
Updated CDK to 2.50.0 in SST 1.17.0
