### ISSUE TITLE
SvelteKit construct?

### ISSUE THREAD

**Issue by tomsharratt** [serverless-stack/sst#2128]
I see you have NextJS constructs. Any plans for a SvelteKit one?

**Comment by fwang** [comment]
Hey @tomsharratt, yup, it's on our roadmap.

Just to clarify, you are looking to deploy SvelteKit with SSR right?

**Comment by fev4** [comment]
This would be great! Specially given that it has reached 1.x

**Comment by fwang** [comment]
Officially released the [`SvelteKitSite`](https://docs.sst.dev/constructs/SvelteKitSite) construct.

Get started here — https://docs.sst.dev/start/svelte
