### ISSUE TITLE
Lambda doesn't support importing modules from a layer when using ESM

### ISSUE THREAD

**Issue by kazdegroot** [serverless-stack/sst#2166]
Due to module resolution ignoring NODE_PATH in ESM mode, the lambda runtime is unable to find the node modules provided by a layer.

This is explained in more detail here, including a workaround: https://github.com/vibe/aws-esm-modules-layer-support

While this is, of course, not an issue with SST itself, I can't find a good way to offload my modules to a layer while using ESM.

I also haven't found a good way to implement the workaround mentioned in the linked article. Because the default asset handler in CDK follows symlinks instead of just including them, that would require changing the handler function to handle the zipping itself, instead of offloading it to CDK, but I don't think that part is easily extensible.

**Comment by jayair** [comment]
We do try to avoid using layers as much as possible. In this case what are you using the layer for?

**Comment by kazdegroot** [comment]
Offloading some modules to a layer cause they're either big or don't deal well with being pulled through a build tool (e.g. pg). I've got it working just using the `nodeModules` option, but it feels significantly less clean than moving all the cruft out of my deployment packages. 

Any specific reason to stay clear of them? They're pretty well documented in the SST docs, and I don't remember any warnings or caveats being included.

**Comment by thdxr** [comment]
There's actually very little runtime advantages to using layers.  It actually can even slow cold starts since we can't bundle things in them efficienly.  It's best to rely on the `nodeModules` option selectively for packages that don't bundle well

**Comment by kazdegroot** [comment]
Ah, well. Then I'll just leave it, and reevaluate if AWS fixes this at some moment. Thanks for effort & the product!

Might be worth it to add some 'best practices' info bubbles to the docs. This is one of a few cases where I've found a 'we don't really use that ourselves due to...' answer while browsing the issues.

**Comment by jayair** [comment]
I think this is being supported: https://aws.amazon.com/blogs/compute/node-js-18-x-runtime-now-available-in-aws-lambda/

**Comment by kazdegroot** [comment]
Seems like it. Any timeline ballpark for SST support for node18 & CDK 2.51?  Is it drop-in, or is it expected to require some work beyond validation, given the use of aws-sdk v3?
