### ISSUE TITLE
Allow partial bind?

### ISSUE THREAD

**Issue by Newbie012** [serverless-stack/sst#2186]
Given the following lines of code:

```typescript
const eventStoreTable = new Table(...);

const eventWriteHandlerLambda = new Function(...);
eventWriteHandlerLambda.attachPermissions([eventStoreTable, "grantReadWriteData"]);

const eventReadHandlerLambda = new Function(...);
eventStreamHandlerLambda.attachPermissions([eventStoreTable, "grantReadData"]);
```

I get the following deprecation notice:

```
WARNING: Passing SST constructs into "permissions" is deprecated, and will be removed in SST v2. Pass them into the "bind" prop. Read more about how to upgrade here — https://docs.serverless-stack.com/upgrade-guide#upgrade-to-v116
```

The problem is that `bind` will give full access to the resource, while I only want to do it partially.

**Comment by Newbie012** [comment]
Hi @fwang,

Wrapping the array inside another array seems to satisfy TypeScript, but it fails in runtime:

```
Error: The specified permissions are not supported
```

![image](https://user-images.githubusercontent.com/10504365/200802172-9940e4e7-c5da-4643-b0d0-d79bfbda6e76.png)

**Comment by fwang** [comment]
Yeah you need to pass in the underlying CDK's construct. Try this
```ts
eventStreamHandlerLambda.attachPermissions([[eventStoreTable.cdk.table, "grantReadData"]]);
```

**Comment by Newbie012** [comment]
Yeah, it seems to be working now. Thanks!
