### ISSUE TITLE
NEXT_PUBLIC_ prefixed environmental variables are not accessible in the Next.js client

### ISSUE THREAD

**Issue by davidrhoderick** [serverless-stack/sst#2189]
**Current behavior**
When I create a `NextJsSite` in SST and assign it environment variables prefixed with `NEXT_PUBLIC_`, I do not have access to them in the Next.js client.

**Expected behavior**
We should be able to access environmental variables that are prefixed with `NEXT_PUBLIC_` from inside the client-side code as per the Next.js [documentation here](https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser).

**Steps to reproduce**

Here's the basic code of what I'm trying to do in the stack:

```
// frontend-stack.ts
export function FrontEndStack({ stack, app }: StackContext) {
  const site = new NextjsSite(stack, 'Site', {
    path: 'frontend',
    environment: {
      NEXT_PUBLIC_REGION: app.region,
      API_URL: 'https://someurl.com',
   }
  });
};
```

Here's the home page in the Next.js application:

```
// frontend/pages/index.js
console.log(process.env);
// This outputs {NEXT_PUBLIC_REGION: app.region, API_URL: 'https://someurl.com'}

const Home = () => {
  console.log(process.env);
  // This outputs { } (an empty object)

  return <h1>Hello world</h1>
}

export default Home;
```

**Comment by davidrhoderick** [comment]
If anyone else is having trouble with this, I added this snippet to my page to pass those variables through as page props:
```
export const getStaticProps = async () => {
  return {
    props: {
      ...Object.keys(process.env).reduce((object, key) => {
        if (key.indexOf('NEXT_PUBLIC_') === 0) {
          object[key] = process.env[key];
        }

        return object;
      }, {}),
    },
  };
};
```
However, it is _not_ ideal because I'd have to do this on every page and wouldn't have access to them from components without passing them down explicitly or adding them to some kind of context.

**Comment by alistairstead** [comment]
I believe that when Next makes the env vars available in the client side code, it does not construct an object that can be destructured process.env is not an object. It would be best if you referenced the full path process.env.NEXT_PUBLIC_ and the value will be populated.

Take a look at https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser

**Comment by davidrhoderick** [comment]
@alistairstead You are 100% correct, my mistake!  Thanks for bearing with me while I forget what I learned before...
