### ISSUE TITLE
Dead link in doc to https://docs.sst.dev/environment-variables

### ISSUE THREAD

**Issue by anderha** [serverless-stack/sst#2191]
Hey, where did the chapter about environment variables move to? If I type 'environment' in your search at https://docs.sst.dev/ I get redirected to https://docs.sst.dev/environment-variables. Which shows me a 404 Page not found.

**Comment by jayair** [comment]
The search is being weird for some reason. We'll have that fixed.

The doc has been merged with https://docs.sst.dev/config. With the .env part here: https://docs.sst.dev/config#other-languages

**Comment by fwang** [comment]
The crawler for doc search (Algolia) stopped working. It's fixed now.
