### ISSUE TITLE
Partition error when deploy to aws china

### ISSUE THREAD

**Issue by LennoxSears** [serverless-stack/sst#2196]
When deploy to aws china. All resource would encounter a problem like this: 
Partition "aws" is not valid for resource "arn:aws:s3:::sstbootstrap-cnnorthwest1f610d23c-25o2doaai7cz/*"

I think the arn should be "arn:aws-cn:s3:::sstbootstrap-cnnorthwest1f610d23c-25o2doaai7cz/*" for region in china.
But I can't find the place to config the partition symbol. If I manully change all files in the .build folder, they will be overide when run "sst deploy".

Can I have any solution to config the arn?

**Comment by fwang** [comment]
Hi @LennoxSears, are you getting this error on deploy? Can you share a screenshot w/ the error?

**Comment by LennoxSears** [comment]
@fwang  Yes, its on deploy. error screenshot is 
![WeChat Image_20221117090948](https://user-images.githubusercontent.com/13961721/202329374-b5cc75c3-7aeb-4774-8998-9aba2776ca2a.png)
deploy successfully with debug stack, but failed with other stacks

**Comment by LennoxSears** [comment]
if anyone can help....

**Comment by LennoxSears** [comment]
really need help 🙏

**Comment by LennoxSears** [comment]
@fwang 😃

**Comment by fwang** [comment]
Sorry about the delay. Taking a look.

**Comment by fwang** [comment]
@LennoxSears this is fixed in SST v2 RC.

SST v2 will be officially release in two weeks.

If you want to give it a try today, here is the migration guide — https://github.com/serverless-stack/sst/tree/sst2/packages/sst#readme
