### ISSUE TITLE
Support Node18.x Runtime

### ISSUE THREAD

**Issue by joshwils82** [serverless-stack/sst#2212]
It appears CDK now has support for the node18.x runtime as of version 2.51.1.  Could you please update SST to also support node18.x runtime?

**Comment by Newbie012** [comment]
I [created a PR](https://github.com/serverless-stack/sst/pull/2206) a few days ago that should support it.

**Comment by fwang** [comment]
Added support for `nodejs18.x` in SST v2.

If you are already using SST v2, update to the latest `sst@snapshot` release.

If you want to give SST v2 a try, we will have an official release candidate next week.
