### ISSUE TITLE
Can we keep Function.permissions?

### ISSUE THREAD

**Issue by lefnire** [serverless-stack/sst#2241]
I see a deprecation warning when I'm using `Function.permissions` and `Function.environment`; saying instead to use `bind` and the former will go away soon. I have some custom CDK stuff, in particular some Docker-based Lambda functions (and likely soon some ECS stuff). I couldn't get `bind` to work with those functions; I'm not sure if it's because bind is an SST concept (not CDK), or if I'm passing the custom resources to `bind` incorrectly. But my solution is of course to just pass the resource to `permissions`, and the resource ARN to `environment` - then handle in my own way in the code. This works, and I'm worried about losing access to this with v2

**Comment by fwang** [comment]
Hey @lefnire, `Function.permissions` is here to stay. You just won't be able to pass in an SST construct into the permissions in v2. Hence the warning.

R u passing in an SST or CDK construct into `permissions`?

**Comment by lefnire** [comment]
got it, that makes sense. I realized I can't just pass CDK constructs (a Docker Lambda function) as `permissions` anyway, and instead needed to `fn.addToRolePolicy()`. So I was misunderstanding permissions. Thanks!
