### ISSUE TITLE
 kysely version miss match causing problems

### ISSUE THREAD

**Issue by rosinbum** [serverless-stack/sst#2251]
There are 2 different versions of kysely (^0.21.6 and ^0.22.0) and kysely-data-ap (^0.1.2 and ^0.1.4) are included in SST. This is causing issues generating SQL. The kysely-codegen needs to be updated to be in line as well. 

The Kysely Discord notes it [here](https://discord.com/channels/890118421587578920/1044646261376155768/1044665224378204170)

all the references are [here](https://github.com/serverless-stack/sst/search?l=JSON&q=kysely&type=code )

**Comment by rosinbum** [comment]
This is related to #2149

**Comment by fwang** [comment]
Thanks @rosinbum. Will prioritize #2149. Closing this for now.
