### ISSUE TITLE
Problems with create-sst@latest

### ISSUE THREAD

**Issue by morcs** [serverless-stack/sst#2259]
I've been having allsorts of problems running `create-sst@latest`, broken dependencies on fundamental things like @babel/core and quitting out in the middle of deployments with no error messages.

I tried different starter templates but all seemed to have different (but similar) issues.

I looked in npm and the `latest` tag is actually pointing at version `0.0.0-20221215185326`. If I run `create-sst@1.18.4` which looks like the latest "proper" version number it all seems fine. I wondered if the tag is wrong?

**Comment by miyamonz** [comment]
I'm also facing the same problem.

**Comment by gabriel-richardson** [comment]
Also facing issues

**Comment by jayair** [comment]
Oof thanks for pointing it out. Taking a look.

**Comment by thdxr** [comment]
this has been fixed thanks for pointing it out
