### ISSUE TITLE
Documentation request - RDS: How to create traditional, non-serverless, Amazon RDS DB instances?

### ISSUE THREAD

**Issue by bjornlll** [serverless-stack/sst#2270]
It seems the RDS construct is limited to creating [Amazon Aurora Serverless v1](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless.html) setups. I would love to see a documented example of how to spin up traditional [Amazon RDS DB instances](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.DBInstance.html).

Please forgive me if this has already been discussed or documented somewhere. I couldn't see it.

**Comment by dangreaves** [comment]
You can use the [aws_rds.DatabaseInstance](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.DatabaseInstance.html) construct directly for this, which includes extensive documentation.

AWS have a [blog post](https://aws.amazon.com/blogs/infrastructure-and-automation/use-aws-cdk-to-initialize-amazon-rds-instances/) showing how to spin up an instance using this construct.

SST is a serverless orientated extension of CDK, so it makes sense that the construct provided by SST is configured in a serverless context, but you can still use all the AWS constructs directly.

See [Can I use all the CDK constructs in SST?](https://docs.sst.dev/faq#can-i-use-all-the-cdk-constructs-in-sst).

**Comment by bjornlll** [comment]
Thanks @dangreaves. That's really helpful. Will close this for now.
