### ISSUE TITLE
Incorrect use of latest npm-dist-tag on @serverless-stack/static-site-env package

### ISSUE THREAD

**Issue by dangreaves** [serverless-stack/sst#2271]
I regularly run `npm outdated` in my projects, to detect outdated dependencies and upgrade them. This process relies on the `latest` npm-dist-tag being set to the _latest stable version_ of the package. As you can see in the screenshot below, npm thinks the latest stable version of @serverless-stack/static-site-env is `0.0.0-20221221034649`, and wants me to upgrade.

![image](https://user-images.githubusercontent.com/1036142/209300197-32ce3acf-e337-4c7c-881b-7f2a32a1c484.png)

According to the [npm-dist-tag](https://docs.npmjs.com/cli/v6/commands/npm-dist-tag) documentation, npm also uses this tag to determine what version to install if you run `npm install <pkg>` without a version.

The published versions can be reviewed on [this page](https://www.npmjs.com/package/@serverless-stack/static-site-env?activeTab=versions).

My suggestion is that the publishing mechanism be updated to set the `--tag` to `snapshot` when publishing those `0.0.0.0` versions, and only set `--tag` to `latest` (or omit) for stable versions.

**Comment by thdxr** [comment]
Hey sorry about this, was an error from our sst2 branch. Fixed now
