### ISSUE TITLE
Reuse existing Cloudfront distribution for StaticSite

### ISSUE THREAD

**Issue by hoangnd25** [serverless-stack/sst#2311]
We currently have a micro frontend setup that I'm looking to convert to use SST StaticSite construct.

In our current setup, the frontend sites are deployed to a single S3 bucket, a single Cloudfront distribution is used to serve the sites (Lambda@Edge is used to route traffic to different paths/folder of the S3 bucket).

If we were to use StaticSite for the sites, we would hit Cloudfront limit for our dev AWS account, as each site would have its own Cloudfront distribution.

I just wonder if there is any issues would prevent us from reusing an existing Cloudfront distribution across our StaticSite constructs?
I saw there is an option to reuse S3 bucket, but it seems to always create new Cloudfront distribution at the moment.

**Comment by fwang** [comment]
Hi Hoang, which CloudFront limit r u running up against?

Frank

--
<https://seed.run/>
Founder at SST <https://sst.dev>

SST <https://github.com/serverless-stack/serverless-stack> - OS framework
for building serverless apps
SEED <https://seed.run/> - Deploy, manage, and monitor serverless apps

**Comment by hoangnd25** [comment]
Hey @fwang

So with our current setup, when someone opens a PR we deploy all the micro frontend apps, which would create more than 10 CF distributions per PR. It will exceed 200 distributions per AWS account limit with our current usage.

There are other ways we could get around the issue (increase quota, more AWS accounts, .etc). However in our case the micro frontends share a lot of behaviours, it also makes sense for them to use a single CF distribution.
