### ISSUE TITLE
Self hosting SST Console

### ISSUE THREAD

**Issue by jbhammon** [serverless-stack/sst#2331]
Hello,

I just discovered this project and I'm pretty excited to give it a try with a project of mine!

The SST Console seems like a great admin tool to get out of the box, similar to Django's admin dashboard. The dev loop seems pretty dependent on having that console available, but it's hosted on `console.sst.dev` rather than something I own/control. Since it's just an SPA, **I'm wondering if it's possible to host the SST console ourselves somehow?** There's not any docs about how that might be done.

I realize that asking about self hosting the console of a serverless, and therefore vendor-dependent, framework might be a little silly, but I am curious. 

If this is something the maintainers would like to provide I'd be happy to contribute to code changes or new docs to support it!

**Comment by thdxr** [comment]
As of today self hosting should be pretty easy. If you go into the console directory and do `pnpm dev` it'll run locally and should just work - it's how we test it.
