### ISSUE TITLE
Deployed Frontend not local Frontend folder

### ISSUE THREAD

**Issue by Lazarus404** [serverless-stack/sst#2339]
Hi guys,

I've gone through the full tutorial and everything seems to work great. However, the frontend doesn't seem to deploy to AWS.  Instead, when I go to the `SiteUrl`, I see the SST logo on a turqoise-ish background with some text.  I'm assuming I must have missed some step, somewhere, but can't find what that is.

Many thanks

**Comment by jayair** [comment]
That's what it looks like when you are working locally. We deploy a placeholder so you can run your frontend through `vite` on your machine. You'll need to do a `sst deploy` at the end, like we do here: https://docs.sst.dev/learn/deploy-to-prod#deploy-with-the-cli

**Comment by Lazarus404** [comment]
Thanks. It seemed strange that a placeholder would be uploaded when running locally, and I guess that's what threw me off.
