### ISSUE TITLE
WebSocketApi Construct: Missing Cloudwatch Permission

### ISSUE THREAD

**Issue by SalhiYassine** [serverless-stack/sst#2354]
It seems quite a few people on discord have run into this issue and I couldn't find an open issue regarding it so I thought I'd open one.

When attempting to run `sst start` or `sst deploy` with a web socket construct, the below occurs:

"CloudWatch Logs role ARN must be set in account settings to enable logging (Service: AmazonApiGatewayV2; Status Code: 400; Error Code: BadRequestException; Request ID ..."

It seems like a policy has been forgotten to be created and linked to the created websocket api.

Hopefully someone can address this soon :)

#### Hacky temporary work around until this is fixed (for those who are stuck):
If you do not care about the logging: pass in `accessLog: false`, as a prop the WebSocketApi construct and you are done.

If you care about the logs:
Once it is deployed (prop still needs to be passed in), you can follow this guide: https://sst.dev/chapters/api-gateway-and-lambda-logs.html
This will take you step by step how add the permission to the api gateway.

Note: you may still need to pass in the accessLog as false to get it to initially deploy and then remove it once you add the permission on the console

Note note: This is a hack to get around it, I am sure there is an official way to do but no one from SST has responded to this exact query that I posted the other day.

The issue explained (My interpretation of it):

- You deploy the API
- It's missing permissions
- It fails to deploy
- the role back deletes the API meaning you cannot add the permission manually

And then the cycle keeps repeating

**Comment by jayair** [comment]
@fwang can you take a look at this when you get a chance?

**Comment by perry-kroma** [comment]
i think i've found a programmatic workaround, i no longer get the "CloudWatch Logs role ARN" error after doing the following:

    import { aws_iam as iam, aws_apigateway as apigw } from "aws-cdk-lib";

    // Do the following code *before* instantiating *any* API gateway (both regular and websocket)

    const role = new iam.Role(stack, "cloudwatch-logs-role", {
      assumedBy: new iam.ServicePrincipal("apigateway.amazonaws.com"),
      managedPolicies: [
        iam.ManagedPolicy.fromAwsManagedPolicyName("service-role/AmazonAPIGatewayPushToCloudWatchLogs"),
      ],
    });

    new apigw.CfnAccount(stack, "cfn-account", {
      cloudWatchRoleArn: role.roleArn,
    });
  
    // Now you can instantiate your API gateways as usual
    const api = new Api(stack, "api", { ... });
    const wssApi = new WebSocketApi(stack, "wssApi", { ... });

**Comment by mixman** [comment]
Thanks! Ran into this when migrating from v1 to v2.

**Comment by fwang** [comment]
Fixed in 2.0.19.

^ added a custom resource that checks if the Role is present. If not, it will create one and attach to API Gateway.

**Comment by kernwig** [comment]
Worked after a teardown and re-deploy. :-/
