### ISSUE TITLE
docs: Code example link directing to 404 Not Found

### ISSUE THREAD

**Issue by jasonrowsell** [serverless-stack/sst#2362]
The following SST.dev pages have links to view code in GitHub for the "Rest API" example:
- https://sst.dev/examples/index.html
- https://sst.dev/examples/how-to-create-a-rest-api-with-serverless.html

However, in the repo, the example has been created under the name `rest-services` instead of `rest-api`. This leads to the user being redirected to GitHub's 404 Page not found.

Proposed solution:
- Recreate example as `rest-api`, replacing `rest-services`

**Comment by jayair** [comment]
Thank you!
