### ISSUE TITLE
Async/Await causes stack to deploy with placeholders instead of code

### ISSUE THREAD

**Issue by ecumene** [serverless-stack/sst#2372]
```js
import { StackContext, Api } from "@serverless-stack/resources";

const function2 = async () => {
}

const function1 = async () => {
  await function2();
}

export async function MyStack({ stack }: StackContext) {
  await function1();

  const api = new Api(stack, "api", {
    routes: {
      "GET /": "functions/lambda.handler",
    },
  });
  stack.addOutputs({
    ApiEndpoint: api.url,
  });
}
```

Reproduction steps:
 1. Have 2-level async-await chain in the stack
 2. npm run build
 3. Check the output, [export function placeholder() {} ](https://github.com/serverless-stack/sst/blob/61207f18a0779eedf93825d207eecd94a37e063b/packages/resources/src/Function.ts#L921) is in the place of real code
 4. Remove the `await`
 5. npm run build
 6. Code is there

https://github.com/ecumene/cursed-async-sst/blob/e908e74414a3c3f16e3dd82eb1b0bd563d38761e/stacks/MyStack.ts#L11

Notes:
 - Using SST v1.18
 - Doesn't happen on debug deploys, only prod deploys
 - Happens on 1.11 but not on 1.10

**Comment by ecumene** [comment]
Looks like this happens on 1.11 but not on 1.10

**Comment by ecumene** [comment]
(very weird) Workaround:

```js
const makeMyStack = (things) => {
  return function MyStack({ stack }: StackContext) {  
    const api = new Api(stack, "api", {
      routes: {
        "GET /": "functions/lambda.handler",
      },
    });
    stack.addOutputs({
      ApiEndpoint: api.url,
    });
  }
}
```
```js
  const things = await function1();
  const stack = makeMyStack(things);
  app.stack(stack);
```

**Comment by fwang** [comment]
Hey @ecumene, for async stacks, you'd need to do this:
```ts
await app.stack(stack);
```

Here's an example — https://docs.sst.dev/constructs/Stack#async-stacks
