### ISSUE TITLE
[SST2 + StaticSite] Using `StaticSite` with a `customDomain` defined calls `buildCommand` twice

### ISSUE THREAD

**Issue by andykenward** [serverless-stack/sst#2399]
When using `StaticSite` defining a `customDomain` will call the `buildCommand` twice when doing a `sst build`or `sst deploy`.

```
sst 2.0.0-rc.57
node v18.13.0
npm 8.19.3
```

**Comment by jayair** [comment]
Yeah you need to commit the cdk.context.json.

**Comment by ruchernchong** [comment]
> Yeah you need to commit the cdk.context.json.

So deploy once first on local and commit the file then let the CI/CD do the rest?

**Comment by jayair** [comment]
Yeah CDK uses that file as a cache.

**Comment by jayair** [comment]
To avoid doing multiple lookups.

**Comment by ruchernchong** [comment]
> Yeah CDK uses that file as a cache.

I see. Thanks for sharing this information.

What about the AWS account number in the ARN? Are they not sensitive to be committed?

**Comment by jayair** [comment]
They should be fine. Nothing credentials related should be in there. https://docs.aws.amazon.com/cdk/v2/guide/context.html

**Comment by ruchernchong** [comment]
> They should be fine. Nothing credentials related should be in there. https://docs.aws.amazon.com/cdk/v2/guide/context.html

Yeah, I read the same guide a few days ago and it appears that AWS themselves are saying it is fine and nothing sensitive.

**Comment by ruchernchong** [comment]
> They should be fine. Nothing credentials related should be in there. https://docs.aws.amazon.com/cdk/v2/guide/context.html

Yeah, I read the same guide a few days ago and it appears that AWS themselves are saying it is fine and nothing sensitive.
