### ISSUE TITLE
Queue with Fifo

### ISSUE THREAD

**Issue by pratikpparikh** [serverless-stack/sst#2414]
When I try to do the following I get the following exception when calling the post:

```
const queue = new Queue(stack, "Queue", {
    consumer: "functions/consumer.main",
    cdk: {
      queue: {
        queueName: "PricingEngineQueue.fifo",
        fifo: true,
      },
    },
  });
```

"The request must contain the parameter MessageGroupId."

**Comment by thdxr** [comment]
When publishing to a FIFO queue you have to specify a MessageGroupId for it to figure out what group it should place the message (for ordering)

If it's just a single group just specify a static group ID

**Comment by pratikpparikh** [comment]
Thank you
