### ISSUE TITLE
start broken when using multiple userPoolIds for authorizer

### ISSUE THREAD

**Issue by MoeQuadrat** [serverless-stack/sst#2417]
when using a cognito authorizer like this 

```ts
export const cognitoAuthorizer = (): ApiGatewayV1ApiAuthorizer => {
	const { cognitoUserPools } = useCognitoStack();
	return {
		type: 'user_pools',
		userPoolIds: [...cognitoUserPools],
	};
}
``` 
and adding multiple userPoolIds SST start/deploy breaks with following 
> Error: There is already a Construct with name 'cognitoAuthorizer-ImportedUserPool' in ApiGatewayV1Api [api]
message

**Comment by fwang** [comment]
Released in v2.0.2
