### ISSUE TITLE
Environment variables specified in Api.defaults.function.environment not being passed to Function

### ISSUE THREAD

**Issue by sebscholl** [serverless-stack/sst#2421]
**Expected behavior:**

When I initialize a new _Api_ construct, I should be able to add environment variables in the _defaults.function_ object that become accessible in my handler using `perocess.env.API_KEY`

```ts
  // Create the HTTP API
  const api = new Api(stack, "FactoryApi", {
    routes: {
      "GET /jobs": "functions/get.handler"
    },
    default: {
    timeout: 90,
    environment: {
      BUCKET_NAME: bucket.bucketName,
    },
    }
  });
```

**What's happening**

The BUCKET_NAME variable never gets added to my function environment. Meanwhile, if I add them directly to the Function construct config, it works.

```ts
  const handler = new Function(stack, "MyFunction", {
    handler: "functions/get.handler",
    timeout: 90,
    environment: {
      BUCKET_NAME: bucket.bucketName,
    },
  });

  // Create the HTTP API
  const api = new Api(stack, "FactoryApi", {
    routes: {
      "GET /jobs": handler,
    },
  });
```

**Where the issue might be**
I believe the issue is happening in here... though haven't been able to spot it. I'll keep looking: https://github.com/serverless-stack/sst/blob/378276800541262623cb894691cf04dfa0550b6e/packages/resources/src/Function.ts#L1315

**Comment by thdxr** [comment]
I believe it should be
```
new APi(..., {
   defaults: {
     function: {
       environment: { ... } 
     }
   }
})
```

considering using TS! it would have caught this error

**Comment by sebscholl** [comment]
Makes sense. Thanks for the reply. By the way, I am using TypeScript! So that's odd.
