### ISSUE TITLE
Console stuck "syncing metadata"

### ISSUE THREAD

**Issue by mclean25** [serverless-stack/sst#2438]
Using SST v2.0.2

![image](https://user-images.githubusercontent.com/7105182/217447853-456fbd10-37b7-4dec-bb56-5027713c5266.png)

**Comment by mclean25** [comment]
Tried completely tearing deleting all my cloudformation stacks (including to bootstraps) and redeploying and still having issues.

**Comment by thdxr** [comment]
I think I may have pushed a fix for this can you try again? If it still doesn't work can you show me a screenshot of the console tab in your browser

**Comment by mclean25** [comment]
Yes, this was fixed. Thanks.

**Comment by mekapotulas** [comment]
Facing this on 2.5.1. 
![image](https://user-images.githubusercontent.com/127547807/231161642-881fc252-35a3-4ab1-adf2-0242e3c2ae97.png)

**Comment by khuezy** [comment]
Can you try it in an incognito tab? If it works in incognito, then you'll want to do a hard refresh + clear cache.

**Comment by mekapotulas** [comment]
Tried in incognito. Stuck as well.

**Comment by xer0x** [comment]
Our SST envs have been stuck on this for ages. Thank you for trying to improve this.
