### ISSUE TITLE
Where are the SST 2.0 release notes?

### ISSUE THREAD

**Issue by joeythomaschaske** [serverless-stack/sst#2450]
I see 2.0 was released 2 days ago but I can't seem to find a document explaining "what's new" or how to upgrade a 1.x app to 2.0

Where can I find supporting documentation?

**Comment by thdxr** [comment]
You can checkout the upgrade guide here: https://docs.sst.dev/upgrade-guide

And we also made a video highlighting some of the features: https://www.youtube.com/watch?v=qEKUNZWbj-8&t=1106s
