### ISSUE TITLE
Cyclic reference error when creating Topic/Queue

### ISSUE THREAD

**Issue by dgocoder** [serverless-stack/sst#2472]
Here is the thread in the help channel of discord.
https://discord.com/channels/983865673656705025/1074112704136085545

Hi, I am trying to share resources between two stacks but am getting a cyclic reference issue. The setup is as follows. I have a shared stack that creates topics. I have another stack that uses that stack to create a queue to subscribe to that topic. 

Stack A
```typescript
export const SharedStack = ({ stack }: SharedContext) => {
  const userCreated = new Topic(stack, "user-created");

  return {
    userCreated,
  };
};
```

Stack B (note: The TopicQueueLambdaStack is just a helper function to standardize a sqs/dlq/lambda model but is just a function)
```typescript
export const PaymentsServiceStack = ({ stack }: StackContext) => {
  const { userCreated } = use(SharedStack);
  TopicQueueLambdaStack({
    stack,
    name: "user-payment",
    topics: [userCreated],
    lambdaFunc: {
      handler:
        "services/payments/cmd/lambdas/user-payment/user-payment.main.go",
    },
  });
};

type TopicQueueLambdaStackContext = {
  stack: Stack;
  name: string;
  topics: Topic[];
  lambdaFunc: FunctionDefinition;
};

export const TopicQueueLambdaStack = ({
  stack,
  name,
  topics,
  lambdaFunc,
}: TopicQueueLambdaStackContext) => {
  const dlq = new Queue(stack, `${name}-dlq`, {
    cdk: {
      queue: {
        retentionPeriod: Duration.days(14),
      },
    },
  });
  const topicQueue = new Queue(stack, `${name}-queue`, {
    cdk: {
      queue: {
        deadLetterQueue: {
          queue: dlq.cdk.queue,
          maxReceiveCount: 1,
        },
      },
    },
    consumer: {
      function: lambdaFunc,
    },
  });

  topics.forEach((topic) => {
    topic.addSubscribers(stack, {
      [topicQueue.queueName]: topicQueue,
    });
  });

  return {
    dlq,
    topicQueue,
  };
};
```
And finally
```typescript

export const Stacks = (app: App) => {
  app.setDefaultFunctionProps({
    runtime: "go1.x",
  });
  app.stack(SharedStack).stack(PaymentsServiceStack);
};
```

As you can see in the thread, I was able to get around the issue by changing the way adding subscribers was called to use cdk. This below causes it to deploy with no issues. The commented out code is what was there before.

```typescript
  topics.forEach((topic) => {
    topic.cdk.topic.addSubscription(new SqsSubscription(topicQueue.cdk.queue));
    // topic.addSubscribers(stack, {
    //   [topicQueue.queueName]: topicQueue,
    // });
  });
```

Looking at the source code: https://github.com/serverless-stack/sst/blob/master/packages/sst/src/constructs/Topic.ts#L425
It appears it is calling the same code I am. Glad I got unblocked but definitely seemed odd and considering it worked with cdk I felt this was an issue currently with sst itself.

**Comment by fwang** [comment]
^ this is being followed up in the Discord thread — https://discord.com/channels/983865673656705025/1074112704136085545

**Comment by dgocoder** [comment]
The issue here after @fwang helped me out was that the key on the adding the subscribers was using the queue name that was yet to be created. Updating the key to as follows avoids this.

```typescript
 topics.forEach((topic) => {
    topic.addSubscribers(stack, {
      [name]: topicQueue, // replacing topicQueue.queueName with the name of the queue that was to be created solved it
    });
  });
```

Closing issue. Once again thanks @fwang
