### ISSUE TITLE
RDS migrations are not being deployed in v2.0.18

### ISSUE THREAD

**Issue by renand05** [serverless-stack/sst#2505]
I am trying to run postgres migrations with SST v2.0.18 but migration scripts are not being recognized. I am having this error: 

{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'index'\nRequire stack:\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'index'",
        "Require stack:",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1000:17)",
        "    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1035:21)",
        "    at async start (file:///var/runtime/index.mjs:1200:23)",
        "    at async file:///var/runtime/index.mjs:1206:1"
    ]
}

I have checked that paths to migrations are properly set up.

**Comment by jayair** [comment]
When do you get this error?

**Comment by renand05** [comment]
I got this error when deploying a stack with an RDS construct which has migrations on it. Those migrations are not being inserted into the database and then I checked logs in the cluster migration function (ClusterMigrationFunction)

**Comment by m4tty-d** [comment]
Experienced the same issue and think I found the reason. See my PR with the fix ☝️

**Comment by renand05** [comment]
I think @m4tty-d that your solution is correct, tnx!...do you know if is possible to fix this temporally and run migrations somehow locally?

**Comment by renand05** [comment]
@thdxr I have upgraded to 2.0.29 but still having the same error. I saw the PR was merged but don´t know if it is ready to use...tnx!

**Comment by renand05** [comment]
@thdxr I have upgraded my sst version to 2.0.30 but I´m getting this error now when deploying: 
Error: Failed to build function "[my_path]/node_modules/support/rds-migrator/index.handler" it seems it is going outside from sst package because of the modification in the path. I think it is caused because in the sst repo RDS.js is inside src/construct and /support is at the root level. However, when checking the node_modules/sst support is at the same leve as constructs.

**Comment by thdxr** [comment]
was in 2.0.30

**Comment by renand05** [comment]
yes 
<img width="796" alt="Captura de Pantalla 2023-02-20 a la(s) 12 15 06 p m" src="https://user-images.githubusercontent.com/26233204/220167931-7f683027-b505-4c37-8da1-6aae4da11cac.png">
