### ISSUE TITLE
File changes in folder `packages` are not being detected to redeploy on Windows

### ISSUE THREAD

**Issue by nhatchaubq** [serverless-stack/sst#2509]
Currently, I have my lambda function code and `schema.graphql` placed in the `packages` folder, for details the structure is like this:
- packages/core
- packages/functions
- packages/graphql/schema.graphql

I expect that when I change any files in `packages` folder, the SST CLI should build and redeploy the changes for me, but it doesn't.
So I have to stop the CLI and run `sst dev` again.
Could you guys help me with this issue?

Also, I discussed with the team about this issue on Discord:
https://discordapp.com/channels/983865673656705025/1075623745022079027

**Comment by harrycollin** [comment]
Experiencing the same problem

**Comment by GinIsTheAnswer** [comment]
Experiencing same with blank project created with npx create-sst@latest

Chaning the "Hello World." to "Hello World!" in packages\functions\src\lambda.ts doesn't update until running dev again.

**Comment by fwang** [comment]
What OS r u using? @harrycollin @GinIsTheAnswer

**Comment by harrycollin** [comment]
@fwang Windows 10 Pro 22H2

**Comment by GinIsTheAnswer** [comment]
Windows 11

**Comment by jayair** [comment]
The PR is in https://github.com/serverless-stack/sst/releases/tag/v2.1.6. I'll close this issue for now? Feel free to reopen if you are still having this problem.
