### ISSUE TITLE
NextjsSite: image optimizer function can't download image (AccessDenied)

### ISSUE THREAD

**Issue by raibima** [serverless-stack/sst#2517]
Images going through the optimizer function are broken in the latest version of SST (2.0.28). jpg & png (and possibly more) are affected. SVGs are not.

Cloudwatch log:
```
ERROR	Failed to download image AccessDenied: Access Denied
    at throwDefaultError (file:///var/task/index.mjs:16751:24)
    at deserializeAws_restXmlGetObjectCommandError (file:///var/task/index.mjs:25060:49)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///var/task/index.mjs:15801:24
    at async file:///var/task/index.mjs:40984:22
    at async file:///var/task/index.mjs:40022:42
    at async file:///var/task/index.mjs:33931:22
    at async file:///var/task/index.mjs:38771:24
    at async downloadHandler (file:///var/task/index.mjs:52986:24)
    at async imageOptimizer2 (file:///var/task/index.mjs:14849:11) 
```

⚠️ **Downgrading to v2.0.27 fixed the issue.**

Minimum code to repro: https://github.com/raibima/img-opt-bug-repro

Manual repro steps:
1. Create a next js site `npx create next-app repro`
2. Initialize SST (drop in mode) `npx create sst && npm install`
3. Load an image using Nextjs Image component `<Image 
4. Deploy app `npx sst deploy --stage prod`

**Comment by khuezy** [comment]
Great catch! SVGs aren't affected b/c they are vectors and don't need to go through any optimizations.
