### ISSUE TITLE
RemixSite - allow esbuild configuration for external

### ISSUE THREAD

**Issue by pehtoorismies** [serverless-stack/sst#2522]
I'm trying to use external dependency with RemixSite, in this case sharp image processing. I've put the sharp in a Lambda layer, but from what I understand it is impossible to use it. The same case applies for any other external package. The reason being that with RemixSite you can not configure `external` option with esbuild. 

https://esbuild.github.io/api/#external
> You can mark a file or a package as external to exclude it from your build. Instead of being bundled, the import will be preserved (using require for the iife and cjs formats and using import for the esm format) and will be evaluated at run time instead.
 
Sharp installation instructions (https://sharp.pixelplumbing.com/install#esbuild) says this package should be set as external.

```
buildSync({
  entryPoints: ['app.js'],
  bundle: true,
  platform: 'node',
  external: ['sharp'], // use sharp as external dependency
})
```

If I look at the `RemixSite.ts` source `external` property is hard coded.

https://github.com/serverless-stack/sst/blob/master/packages/sst/src/constructs/RemixSite.ts#L140

```
const result = esbuild.buildSync({
      entryPoints: [serverPath],
      bundle: true,
      target: "node16",
      platform: "node",
      external: ["aws-sdk"],
      outfile: path.join(outputPath, "server.js"),
      // We need to ensure that the polyfills are injected above other code that
      // will depend on them. Importing them within the top of the lambda code
      // doesn't appear to guarantee this, we therefore leverage ESBUild's
      // `inject` option to ensure that the polyfills are injected at the top of
      // the bundle.
      inject: [polyfillDest],
    });
```

Is there a workaround?

**Comment by SpencerDuball** [comment]
I don't believe there is an option for this at the moment but would affect this issue too as the ability to query a PostgreDB needs the `pg` package. This has a dependency on `pg-native` which we would need esbuild configuration in order to deploy: https://github.com/serverless-stack/sst/issues/2412

**Comment by jayair** [comment]
I'll ask Frank to take a look at this.

**Comment by kazdegroot** [comment]
I just fixed this with `patch-package`, by adding the relevant packages to the array passed to the `external` argument of `createServerLambdaBundle` in `RemixSite.js`, though that isn't a very durable solution.

Seems like this might be resolved by changing the relevant lines to be something like:
```ts
const { runtime: runtimeRaw, timeout, memorySize, environment, cdk, external = [] } = this.props;
// ...
const bundlePath = this.createServerLambdaBundle("regional-server.js", runtime === "nodejs18.x" ? external : ["aws-sdk", ...external]);
```

If that seems like a good solution, I could put an MR in.

**Comment by fwang** [comment]
It seems it's always those few trouble makers, namely `sharp` and `pg`. I'm planning to automatically add them as external if they are detected. I can get this in this week.

Any other packages we should add to the list?

**Comment by kazdegroot** [comment]
I've been experimenting with [postgres](https://github.com/porsager/postgres), which also attempts to include `pg-native`.

**Comment by SpencerDuball** [comment]
@fwang I think this would be great and could solve the issue of postgres causing remix to not build correctly. Just for clarification I believe we would only need to add `pg-native` to the external list, not `pg` itself. Here is an esbuild issue that captures other running into this and the solution too: https://github.com/brianc/node-postgres/issues/2800

@kazdegroot I have looked at quite a few ORMs/libraries to connect to postgres and I think all of them use `pg` somewhere down the line (which is trying to include `pg-native`) so I believe this addition would fix the build issues from the package you linked and (hopefully) all others.

This would fix the issue I created here #2412 as well btw.

**Comment by kazdegroot** [comment]
@SpencerDuball Just tried that, and seems like excluding just `pg-native` works. Apparently went a bit over-eager there. 

Though `postgres` does not use `pg`; it also does not seem to use `pg-native`, but it was still causing bundling errors when I was only excluding `pg`, so that's interesting.

**Comment by fwang** [comment]
Just released 2.1.21.

SST will auto detect `sharp` and `pg-native`, mark them as externals, and bundle them in `node_modules`.

Side node.. now you can also pass in `nodejs` like this, but that shouldn't be necessary to get `sharp` and `pg-native` to work.
```ts
  const site = new RemixSite(stack, "regional", {
    path: "sites/remix",
    bind: [f, s],
    environment: {
      FUNCTION_NAME: f.functionName,
    },
    nodejs: {
      install: ["sharp"],
      format: "cjs",
      esbuild: { ... },
    },
  });
```

**Comment by fwang** [comment]
Lemme know if this works.
cc @SpencerDuball @kazdegroot @pehtoorismies

**Comment by kazdegroot** [comment]
@fwang Just redeployed after removing my patch and updating, and everything seems to be working great. Thanks!

**Comment by pehtoorismies** [comment]
Just writing this as a FYI. I ended up using a lambda layer with RemixSite. The solution is a bit cumbersome since it is not possible to add any lambda layers with `RemixSite` constructor or `stack.addDefaultFunctionLayers()`. 

```typescript
export const RemixStack = ({ stack, app }: StackContext) => {
  // create layer
  const sharpLayer = new lambda.LayerVersion(
    stack,
    `${app.stage}-SharpLayer'`,
    {
      code: lambda.Code.fromAsset('stacks/layers/sharp'),
      compatibleArchitectures: [lambda.Architecture.ARM_64],
    }
  )
  
  // create RemixSite
  const site = new RemixSite(stack, 'remix-site', {
    // needed for layer to work
    nodejs: {
      esbuild: {
        external: ['sharp'],
      },
    },
  })
  
  // a bit smelly solution to add layer to Remix-handler lambda
  const serverHandler = site.cdk?.function as lambda.Function
  serverHandler.addLayers(sharpLayer)
 
  stack.addOutputs({
    URL: site.url ?? 'localhost',
  })
}

**Comment by derrick-null** [comment]
I was trying to add Sharp to my remix app and had the same issue. I added the configuration to the sst.aws.Remix:
`
nodejs: {
        install: ["sharp"],
        // loader: {
        //   ".node": "binary",
        // },
        esbuild: {
          external: ["sharp"],
        },
      },
`
The sst console got the following error:
`
06:50.641
Unknown application error occurred
Runtime.Unknown
12:06:52.414
Uncaught Exception	{
  "errorType": "Error",
  "errorMessage": "Could not load the \"sharp\" module using the linux-x64 runtime\nPossible solutions:\n- Ensure optional dependencies can be installed:\n    npm install --include=optional sharp\n    yarn add sharp --ignore-engines\n- Ensure your package manager supports multi-platform installation:\n    See https://sharp.pixelplumbing.com/install#cross-platform\n- Add platform-specific dependencies:\n    npm install --os=linux --cpu=x64 sharp\n- Consult the installation documentation:\n    See https://sharp.pixelplumbing.com/install",
  "stack": [
    "Error: Could not load the \"sharp\" module using the linux-x64 runtime",
    "Possible solutions:",
    "- Ensure optional dependencies can be installed:",
    "    npm install --include=optional sharp",
    "    yarn add sharp --ignore-engines",
    "- Ensure your package manager supports multi-platform installation:",
    "    See https://sharp.pixelplumbing.com/install#cross-platform",
    "- Add platform-specific dependencies:",
    "    npm install --os=linux --cpu=x64 sharp",
    "- Consult the installation documentation:",
    "    See https://sharp.pixelplumbing.com/install",
    "    at Object.<anonymous> (/var/task/node_modules/sharp/lib/sharp.js:114:9)",
    "    at Module._compile (node:internal/modules/cjs/loader:1369:14)",
    "    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)",
    "    at Module.load (node:internal/modules/cjs/loader:1206:32)",
    "    at Module._load (node:internal/modules/cjs/loader:1022:12)",
    "    at Module.require (node:internal/modules/cjs/loader:1231:19)",
    "    at require (node:internal/modules/helpers:179:18)",
    "    at Object.<anonymous> (/var/task/node_modules/sharp/lib/constructor.js:10:1)",
    "    at Module._compile (node:internal/modules/cjs/loader:1369:14)",
    "    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)"
  ]
}
`
I checked the source code and found the npm install command in the .sst/platform/src/runtime/node.ts is incorrect.
`
if (installPackages.includes("sharp")) {
        cmd.push(
          "--platform=linux",
          input.architecture === "arm64" ? "--arch=arm64" : "--arch=x64",
        );
      }
`
According to the docs of sharp : https://sharp.pixelplumbing.com/install#cross-platform
I changed the code to:
`
if (installPackages.includes("sharp")) {
        cmd.push(
          "--platform=linux",
          input.architecture === "arm64"
            ? "--arch=arm64"
            : "--cpu=x64 --os=linux",
        );
      }
`
Then the sharp installed correctly.
