### ISSUE TITLE
Python example is broken

### ISSUE THREAD

**Issue by rjerue** [serverless-stack/sst#2530]
Hey,

Trying to deploy a python lambda to my project. Seems to be dead on arrival. Decided to try running the python example and have run into similar issues.

The example is kinda broken, but the default handler still deploys. I'm open to fixing the example if I can test it properly.

```
npx create-sst@latest --template=examples/rest-api-python

cd my-app --whatever you named it
pnpm install
pnpm dev
```

Then try to run the lambda in any way locally.
- from the sst console
- from going to the api gateway url (should just be a GET)

The error I get is:

```
|  Invoked functions/lambda.handler
|  +84ms   Traceback (most recent call last):
|  +84ms     File "/Users/rjerue/dev/sst-python-ex/node_modules/sst/support/python-runtime/runtime.py", line 73, in <module>
|  +85ms   context = Context(
|  +85ms                 ^^^^^^^^
|  +85ms     File "/Users/rjerue/dev/sst-python-ex/node_modules/sst/support/python-runtime/runtime.py", line 30, in __init__
|  +85ms       self.identity = Identity(**json.loads(identity))
|  +85ms                                  ^^^^^^^^^^^^^^^^^^^^
|  +85ms     File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 339, in loads
|  +85ms       raise TypeError(f'the JSON object must be str, bytes or bytearray, '
|  +85ms   TypeError: the JSON object must be str, bytes or bytearray, not NoneType
```

Expected result: should say "Hello world"

**Comment by rjerue** [comment]
Fix for it is:

```python
if (identity != None):
            self.identity = Identity(**json.loads(identity))
```

I think this field is used by cognito and might not always exist

in `sst/support/python-runtime/runtime.py`... will see if I can PR and put up the examples.

**Comment by rjerue** [comment]
So while that fixes the above, when I invoke from the console the event and context are barren... aws fills those in though if I go to the url. Could just be my misunderstanding in how it all works

**Comment by rjerue** [comment]
https://github.com/serverless-stack/sst/issues/2530 trying to fix the python example for this and banging my head against the wall. I'm not really a python expert either... just have a project with a bunch of preexisting lambdas I'd like to reuse. changed example package to look like this. The "hello" lambda has no dependency, the "functions" one is similar to the example.

The project only runs correctly if requirements.txt is at the root of the file. Otherwise, I get strange errors like this even though it clearly exists:

```
Error: Could not find src for packages/hello/lambda.handler

Trace: Error: Could not find src for packages/hello/lambda.handler
    at Object.startWorker (file:///Users/rjerue/dev/rest-api-python/node_modules/sst/runtime/handlers/python.js:46:23)
    at async Object.cb (file:///Users/rjerue/dev/rest-api-python/node_modules/sst/runtime/workers.js:39:9)
    at process.<anonymous> (file:///Users/rjerue/dev/rest-api-python/node_modules/sst/cli/sst.js:58:17)
    at process.emit (node:events:402:35)
    at processEmit [as emit] (/Users/rjerue/dev/rest-api-python/node_modules/signal-exit/index.js:199:34)
    at process._fatalException (node:internal/process/execution:170:25)
    at processPromiseRejections (node:internal/process/promises:246:11)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)

Need help with this error? Join the SST community on Discord https://sst.dev/discord
```

Now, if I put the requirements.txt in the same folder of the lambda, I get a different error:

```
|  Invoked packages/hello/lambda.handler
|  +123ms  Traceback (most recent call last):
|  +124ms  File "/Users/rjerue/dev/rest-api-python/node_modules/sst/support/python-runtime/runtime.py", line 89, in <module>
|  +124ms      module = import_module(args.handler_module)
|  +124ms               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|  +124ms    File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 121, in import_module
|  +124ms      raise TypeError(msg.format(name))
|  +124ms  TypeError: the 'package' argument is required to perform a relative import for '.lambda'
|  Error: the 'package' argument is required to perform a relative import for '.lambda'
     File "/Users/rjerue/dev/rest-api-python/node_modules/sst/support/python-runtime/runtime.py", line 89, in <module>
    module = import_module(args.handler_module)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

     File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 121, in import_module
    raise TypeError(msg.format(name))
```

Even with all that, I'm skeptical that it'll run in the lambda if I keep it in the root.

Though it doesn't let me deploy:

```
➜ rest-api-python (main) ✗ npx sst deploy --stage prod
SST v2.0.33

➜  App:     rest-api-python
   Stage:   prod
   Region:  us-east-1
   Account: 461967551600

Error: Invalid src or dest: cp returned undefined (cannot copy /Users/rjerue/dev/rest-api-python to a subdirectory of self /Users/rjerue/dev/rest-api-python/.sst/artifacts/c87642d2197ff795af7529ce8b101ee4dc72b47e10) /Users/rjerue/dev/rest-api-python/.sst/artifacts/c87642d2197ff795af7529ce8b101ee4dc72b47e10

Trace: SystemError [ERR_FS_CP_EINVAL]: Invalid src or dest: cp returned undefined (cannot copy /Users/rjerue/dev/rest-api-python to a subdirectory of self /Users/rjerue/dev/rest-api-python/.sst/artifacts/c87642d2197ff795af7529ce8b101ee4dc72b47e10) /Users/rjerue/dev/rest-api-python/.sst/artifacts/c87642d2197ff795af7529ce8b101ee4dc72b47e10
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at new SystemError (node:internal/errors:233:5)
    at new NodeError (node:internal/errors:336:7)
    at checkPaths (node:internal/fs/cp/cp:108:11)
    at async cpFn (node:internal/fs/cp/cp:67:17)
    at async Object.build (file:///Users/rjerue/dev/rest-api-python/node_modules/sst/runtime/handlers/python.js:94:13)
    at async task (file:///Users/rjerue/dev/rest-api-python/node_modules/sst/runtime/handlers.js:34:31)
    at async Object.build (file:///Users/rjerue/dev/rest-api-python/node_modules/sst/runtime/handlers.js:78:23)
    at async file:///Users/rjerue/dev/rest-api-python/node_modules/sst/constructs/Function.js:189:32
    at process.<anonymous> (file:///Users/rjerue/dev/rest-api-python/node_modules/sst/cli/sst.js:58:17)
    at process.emit (node:events:402:35)
    at process.emit (node:domain:475:12)
    at process._fatalException (node:internal/process/execution:170:25)
    at processPromiseRejections (node:internal/process/promises:246:11)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)

Need help with this error? Join the SST community on Discord https://sst.dev/discord
```

Not really sure what direction to go here

**Comment by rjerue** [comment]
Ok, I've got a version that at least publishes.

Trick was to make the file structure look like:
<img width="326" alt="image" src="https://user-images.githubusercontent.com/4666313/220457366-262265d8-b817-41fa-86f3-4848ab29048e.png">

And use the function construct rather than the inline json definition. Dependencies not installing now.

**Comment by kardosorsi** [comment]
Hey, thank you for your work on the broken example! Following up on this issue as we would like to use python lambdas in our project with dependencies. Will there be a fix for that in the near future or can you please help me out with alternatives that worked for you?

**Comment by rjerue** [comment]
https://github.com/serverless-stack/sst/commit/2c332911ffa2ee6d6d459ab2464dc21cd04c9405 fixed the invocation issues I was having. I ended up putting my deps in a layer and haven't changed it away from that.

**Comment by ClemensJakob** [comment]
@rjerue How did you manage to put the dependencies in a layer? Could you provide an example?

Thank you!

**Comment by kardosorsi** [comment]
@ClemensJakob I managed to do it without layers.
sst version 2.1.6 and a folder structure of:
![Screenshot from 2023-03-14 15-23-37](https://user-images.githubusercontent.com/14195718/225031651-2d71e931-480f-4bec-8884-e080e3a5b079.png)

**Comment by ClemensJakob** [comment]
Thanks @kardosorsi!

I'm trying to get it runnign with your folder structure. How is your API / Function construct built? Mine currently looks like this:

`  const api = new Api(stack, "api", {
    routes: {
      "GET /talks": new Function(stack, "ListTalks", {
        handler: `packages/functions/src/lambda.handler`,
        runtime: "python3.8",
        python: {
          installCommands: ["pip install -r requirements.txt"],
        },
      }),
    },
  });`

**Comment by kardosorsi** [comment]
I don't have the python: { installCommands... part, but otherwise the same.

**Comment by ClemensJakob** [comment]
Now it works, thank you!
