### ISSUE TITLE
Create a SvelteKit  construct

### ISSUE THREAD

**Issue by lukeshay** [serverless-stack/sst#2547]
Not sure what to leave in the comments here but it would be cool if there was a SvelteKit construct. An adapter would have to be written similarly to how Astro works - <https://kit.svelte.dev/docs/writing-adapters>.

I would be willing to work on the adapter if help is wanted.

**Comment by okrsnak** [comment]
Duplicity with #2128

**Comment by hmprt** [comment]
Also registering our interest in a SvelteKit component!

**Comment by jayair** [comment]
@hmprt leave a message in here? https://github.com/serverless-stack/sst/issues/2128

**Comment by fwang** [comment]
Officially released the [`SvelteKitSite`](https://docs.sst.dev/constructs/SvelteKitSite) construct.

Get started here — https://docs.sst.dev/start/svelte
