### ISSUE TITLE
V2. Regression. No way to set `--outputs-file`

### ISSUE THREAD

**Issue by o-alexandrov** [serverless-stack/sst#2576]
As the title says, in v2, `--outputs-file` is ignored.
The following example has no effect.

`sst --outputs-file "./example.json"`

**Comment by thdxr** [comment]
So we always generate an outputs file now inside the `.sst` folder - do you need the ability to configure specifically where it goes?

**Comment by o-alexandrov** [comment]
[AWS recommends to have a multi-account architecture.](https://docs.aws.amazon.com/whitepapers/latest/organizing-your-aws-environment/organizing-your-aws-environment.html) When having multiple AWS accounts managed with SST, you’d want to have different output filename per AWS account as you might have stacks with the same names within an SST managed deployment (app).

**Comment by thdxr** [comment]
got it I'll add it back in

**Comment by zhex900** [comment]
when can you add it back in?

**Comment by klindklind** [comment]
I'd also vote for restoring the `--outputs-file` option 🙏

**Comment by o-alexandrov** [comment]
If possible, please kindly add `outputsFile` to `ConfigOptions` for consistency with other options.
So in other words, it'd be in `sst.config.ts`:

```ts
export default {
  config: () => ({ outputsFile })
}
```

**Comment by iDVB** [comment]
@thdxr was this ever added back in?

**Comment by thdxr** [comment]
I added an `outputs` field in the config in the latest release
