### ISSUE TITLE
Deployment fails with AWS::ApiGatewayV2::Stage CREATE_FAILED The following context variables are not supported: [$context.identity.cognitoIdentityId]

### ISSUE THREAD

**Issue by ttarhan** [serverless-stack/sst#2587]
Deploying any SST (create, not update) in us-west-2 results in:

AWS::ApiGatewayV2::Stage CREATE_FAILED The following context variables are not supported: [$context.identity.cognitoIdentityId]

Presumably, the change @ AWS that results in this failure will come to other regions shortly.

Root cause:

It is not valid in HTTP APIs to use $context.identity.cognitoIdentityId in a log statement, as HTTP APIs do not support direct integration with Cognito. The AWS create-stage API was recently updated such that attempting to use $context.identity.cognitoIdentityId in a log format results in an error when creating a stage. It was never possible for $context.identity.cognitoIdentityId to work, and so removing it should be harmless.

Note the AWS docs on this are wrong. [This page](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-logging-variables.html) claims it's valid to use $context.identity.cognitoIdentityId, but [this page](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-vs-rest.html) makes it clear that HTTP APIs do not support direct Cognito integration.

Furthermore, the AWS Console makes it clear you cannot add a Cognito authorizer to an HTTP API (whereas you can to a REST API).

**Comment by AbdullhRtima** [comment]
I got the same error 
`  Status: failed
  Error: The following context variables are not supported: [$context.identity.cognitoIdentityId] (Service: AmazonApiGatewayV2; Status Code: 400; Error Code: BadRequestException; Request ID: baff5a3d-145c-4da3-a900-3b6e073dd528; Proxy: null)`

**Comment by ashraf-revo** [comment]
we can disable logs in our apps until this pr merged by using accessLog: false in the Api Props definations

**Comment by nigelatdas** [comment]
I'm getting same error.

**Comment by fwang** [comment]
Fixed in v2.1.9

**Comment by krmorse** [comment]
Any plans to fix in v1?
