### ISSUE TITLE
v2.1.7 seems to be broken

### ISSUE THREAD

**Issue by jolo-dev** [serverless-stack/sst#2597]
It seems that v2.1.7 is broken. When downgrading it works.
I used pnpx create-sst@latest --template=base/example my-app and tried with pnpm i and npm i.
Actually, I also tried the tutorial https://sst.dev/examples/how-to-create-a-rest-api-with-serverless.html
I use node v18.14.2 (npm v9.5.0)
https://app.warp.dev/block/iPZMONi6CEgv5VAjU2HIan

**Comment by jayair** [comment]
I think we fixed it here: https://github.com/serverless-stack/sst/releases/tag/v2.1.8

**Comment by jolo-dev** [comment]
@jayair Yes, it's working now. But you are at v2.1.12 now. Did I sleep so long? :D
