### ISSUE TITLE
[docs] Wrong instructions to test API Endpoints

### ISSUE THREAD

**Issue by zvictor** [serverless-stack/sst#2598]
I was trying to follow the [instructions to test API Endpoints](https://docs.sst.dev/testing#testing-api-endpoints), but it seems to be incorrect.

It tells us to make use of `new Config.Parameter`, but I am afraid this doesn't exist.
Am I getting it wrong or is the documentation incorrect/outdated?

**Comment by jayair** [comment]
It sounds like you figured it out?

**Comment by zvictor** [comment]
Oh yes! I just forgot to open the PR. I am sorry.

https://github.com/serverless-stack/sst/pull/2607
