### ISSUE TITLE
[SST-90] Test issue

### ISSUE THREAD

**Issue by thdxr** [serverless-stack/sst#2630]
Foo bar foo

<sub>From [SyncLinear.com](https://synclinear.com) | [SST-90](https://linear.app/sst-dev/issue/SST-90/test-issue)</sub>

**Comment by thdxr** [comment]
Hello

**Comment by thdxr** [comment]
Bye

**Comment by thdxr** [comment]
Foo

**Comment by jayair** [comment]
Commenting from GH

**Comment by fwang** [comment]
test3

**Comment by jayair** [comment]
New comment

**Comment by jayair** [comment]
From GH

**Comment by fwang** [comment]
test 4 from GH
