### ISSUE TITLE
[SST-134] `npx sst update` does not exit

### ISSUE THREAD

**Issue by twiddler** [serverless-stack/sst#2653]
```console
$ npx sst update 2.1.26
```

does not exit. Its last message is

>➜  Make sure to run: npm install (or pnpm install, or yarn)

or

>✔  Already using v2.1.26

but the command does not exit. I need to Ctrl+C out of it.

<sub>[SST-134](https://linear.app/sst-dev/issue/SST-134/npx-sst-update-does-not-exit)</sub>

**Comment by jayair** [comment]
Oh that's weird.

**Comment by jayair** [comment]
We'll take a look.

**Comment by twiddler** [comment]
Same thing happens with other `sst` commands as well. Maybe it's just my machine? :thinking:

**Comment by jayair** [comment]
Which version of npm and Node btw?

**Comment by twiddler** [comment]
```console
$ npm --version
9.5.0
$ pnpm --version
7.30.0
$ node --version
v19.7.0
```

Tried node v18.14.2 (same npm and pnpm versions as above). Does not hang. Seems to be a node v19 thing.
