### ISSUE TITLE
Using existing HttpApi from advanced examples doesn't work

### ISSUE THREAD

**Issue by dev-cyprium** [serverless-stack/sst#2695]
I'm using the following versions in my `package.json`

```json
"devDependencies": {
    "@tsconfig/node16": "^1.0.3",
    "aws-cdk-lib": "2.62.2",
    "constructs": "10.1.156",
    "sst": "^2.2.6",
    "typescript": "^5.0.2"
  },
  ```
  
  It seems that the documentation here is not correct:
  https://docs.sst.dev/advanced/importing-resources
  ```ts
  import { HttpApi } from "@aws-cdk/aws-apigatewayv2";

new Api(stack, "Api", {
  httpApi: HttpApi.fromHttpApiAttributes(stack, "ExistingApi", {
    httpApiId,
  }),
  routes: {
    "GET /new": "src/lambda.main",
  },
});
```

It mentions that you need to import from `@aws-cdk` which doesn't have that function. Adding `aws-cdk` as a dependency still doesn't solve this issue, as if you try to do so:
![image](https://user-images.githubusercontent.com/6002628/226693730-0f0e8598-d744-4489-a160-5b5e50182711.png)

The reason I need this is because I have a legacy `serverless.yaml` app, which I want to migrate to use SST. However, with this problem this doesn't seem possible, as I'm not sure how to overcome this issue. The documentation seems to contradict itself, since it mentions that you don't need `aws-cdk` and then, in this example it seems to reference from it.

Any plans to address this issue?

**Comment by dev-cyprium** [comment]
Looks like the documentation should simply be updated to look like this, (also might need to explain or see why we need `@aws-cdk` 

```ts
import { StackContext, Api } from 'sst/constructs';
import { HttpApi } from '@aws-cdk/aws-apigatewayv2-alpha';

export function API({ stack }: StackContext) {
  new Api(stack, 'KaznaServisAPI', {
    cdk: {
      httpApi: HttpApi.fromHttpApiAttributes(stack, 'HttpApi', {
        httpApiId: 'api-id',
      }),
    },
  });
}

```

**Comment by dev-cyprium** [comment]
https://github.com/serverless-stack/sst/pull/2696

**Comment by fwang** [comment]
Thanks @dev-cyprium!
