### ISSUE TITLE
IoT core creates noticable more cost than the websocket solution pre v2.0 

### ISSUE THREAD

**Issue by SchmellaKaa** [serverless-stack/sst#2715]
Im working with sst for quite a while now and since march i upgraded a project to sst 2.0. 
What i noticed is, that this month the pricing rose quite a bit. I looked into it, and it seems, that IoT Core (which replaced the custom websocket server that was created on every project before 2.0).
During this month i accumulated around 5 Million IoT messages which translates to a cost about 7 USD. 

![image](https://user-images.githubusercontent.com/27963607/228240142-bbfce951-3105-4205-a546-8622194efe53.png)

Has anyone else noticed this? This is not a big amount of money, but when changing to sst2.0 i didn't see this "development" cost increase mentioned anywhere, so i thought i mention it here.

**Comment by jayair** [comment]
That's a bit too high. Can you post about this over on #help in Discord?

**Comment by mixman** [comment]
Related Discord thread: https://discord.com/channels/983865673656705025/1090559304450457643/1090559304450457643

**Comment by jayair** [comment]
Yup we'll look at it there. It should've been fixed in the recent releases.
