### ISSUE TITLE
`sst dev` fails to return payload over a certain size

### ISSUE THREAD

**Issue by jensonb** [serverless-stack/sst#2723]
We have a function in our SST app that crashes lambda local `sst dev` mode. It functions properly when it has been deployed to aws with `sst deploy`.
Minimal test reproduction: https://github.com/jensonb/sst-local-payload-bug
Discord thread: https://discord.com/channels/983865673656705025/1091177378513948713

The bug seems related to payload size. In my minimal reproduction, the failure seems to start once the response payload reaches ~80kB.

When the function blows up, `sst dev` becomes unresponsive. The request receives a `{"message":"Internal Server Error"}` error response after a long hang, and further API requests (including to other routes) receive the error about sst dev not running. Killing the process and restarting is the only solution I have found.

## Expected Behavior

The function should behave the same whether running locally after `sst dev` or on aws after `sst deploy`. `sst dev` should be able to respond with payloads that are not larger than the 6MB lambda payload limit.

## Current Behavior

When the function has been deployed with `sst dev`, the larger responses are handled properly. When the function is running in `sst dev` mode, the function will hang then return a `{"message":"Internal Server Error"}` response, after which the `sst dev` session becomes completely unresponsive to further requests. Small payloads behave consistently between the two modes, the issue is only once the payload surpasses around 80kB.

## Steps to Reproduce

1. Clone the minimal reproduction from https://github.com/jensonb/sst-local-payload-bug
2. (optional) Select nodejs version: `nvm use`
3. Install dependencies: `yarn`
4. Start local lambda mode: `yarn sst dev`
5. Visit `{API_GATEWAY_URL}/test/1` in your browser. Repeat for tests 2-5. Tests 4 and 5 should crash the `sst dev` session.
6. Deploy to aws: `yarn sst deploy`
7. Repeat step 5, all test cases work this time!
8. Cleanup: `yarn destroy`

## Context (Environment)

```
node: v18.12.1
SST: v2.3.5
CDK: v2.62.2
```
This bug makes `sst dev` keep crashing when using a certain part of our app, forcing us to resort to constantly re-deploying for lambda code changes.

edit: markdown formatting
edit: add link to thread in Discord

**Comment by jensonb** [comment]
I also tried greatly increasing the lambda function timeout. This did not fix the issue, and `sst dev` crashed long before the timeout.

**Comment by jayair** [comment]
Did you post this Discord? Cos I think I saw this there. I'll get the team to take a look.

**Comment by jensonb** [comment]
@jayair Yes I did post it on the discord, and you tagged Dax on there. Here's the link to the post: https://discord.com/channels/983865673656705025/1091177378513948713 and I'll edit the issue to include as well.

**Comment by jensonb** [comment]
Updating with information discovered during discussions in Discord:

The problem seems related to the iot message payload max size. Making the following change in `node_modules/sst/iot.js` resolves the issue:

```diff
- const parts = json.match(/.{1,100000}/g);
+ const parts = json.match(/.{1,50000}/g);
```

Additional context:
- before changing iot.js, my payload with length 88337 would respond successfully
- before changing iot.js, my payload with length 98149 would hang the process every time

I'll get you guys a PR with test coverage hopefully, might not get to it until the weekend though.

TODO:

- [ ] decrease message chunk to 50kb
- [ ] implement test up to 6mb (lambda payload limit)
- [ ] update live lambda docs reference to 100kb message chunks (in how it works)

**Comment by jensonb** [comment]
misclick

**Comment by jensonb** [comment]
PR ready for review.
