### ISSUE TITLE
sst bind always returns status code 0

### ISSUE THREAD

**Issue by RobbeCl** [serverless-stack/sst#2724]
Since this pr: https://github.com/serverless-stack/sst/pull/2710/files the sst bind command does not hang anymore, which is great! But now when running the command against vitest, it always returns a status code of 0 instead of 1, even though are tests are failing. I think you forgot to pass the status code of the child process to the `process.exit` call.

**Comment by fwang** [comment]
Will do

**Comment by fwang** [comment]
Fixed in v2.3.6
