### ISSUE TITLE
Package aws-cdk-lib/constructs version mismatch causing type error

### ISSUE THREAD

**Issue by JakeTompkins** [serverless-stack/sst#2729]
Hey, I'm migrating a typescript project from aws-cdk to sst version 2.3.6 and it seems there's a mismatch between the versions of the cdk 'constructs' package used that's causing a type error when I try to pass an instance of sst.Stack into sst.Function.

Specifically, it's reporting that the type of Construct between versions 10.1.156 and 10.1.298 seem to differ.

code: (I unfortunately can't provide a full example due to privacy obligations, but this is the line that's throwing an error, where `scope` is type `sst.Stack`)
`    const newLambda = new sst.Function(scope, `${name}Handler`, { `

The type error:

```Argument of type 'Stack' is not assignable to parameter of type 'Construct'.  Types of property 'node' are incompatible.    Type 'import("<redacted_path_to_project>/node_modules/.pnpm/constructs@10.1.298/node_modules/constructs/lib/construct").Node' is not assignable to type 'import("<redacted_path_to_project>/node_modules/.pnpm/constructs@10.1.156/node_modules/constructs/lib/construct").Node'.      Types have separate declarations of a private property 'host'.```

`pnpm why constructs`

```
Legend: production dependency, optional only, dev only

infrastructure@1.0.0 /Users/jake/code/Symply/symply-payroll-v2/infrastructure

dependencies:
aws-cdk-lib 2.62.2
└── constructs 10.1.298 peer
sst 2.3.6
├─┬ @aws-cdk/aws-apigatewayv2-alpha 2.62.2-alpha.0
│ ├─┬ aws-cdk-lib 2.62.2 peer
│ │ └── constructs 10.1.298 peer
│ └── constructs 10.1.298 peer
├─┬ @aws-cdk/aws-apigatewayv2-authorizers-alpha 2.62.2-alpha.0
│ ├─┬ @aws-cdk/aws-apigatewayv2-alpha 2.62.2-alpha.0 peer
│ │ ├─┬ aws-cdk-lib 2.62.2 peer
│ │ │ └── constructs 10.1.298 peer
│ │ └── constructs 10.1.298 peer
│ ├─┬ aws-cdk-lib 2.62.2 peer
│ │ └── constructs 10.1.156 peer
│ └── constructs 10.1.156 peer
├─┬ @aws-cdk/aws-apigatewayv2-integrations-alpha 2.62.2-alpha.0
│ ├─┬ @aws-cdk/aws-apigatewayv2-alpha 2.62.2-alpha.0 peer
│ │ ├─┬ aws-cdk-lib 2.62.2 peer
│ │ │ └── constructs 10.1.298 peer
│ │ └── constructs 10.1.298 peer
│ ├─┬ aws-cdk-lib 2.62.2 peer
│ │ └── constructs 10.1.156 peer
│ └── constructs 10.1.156 peer
├─┬ aws-cdk-lib 2.62.2
│ └── constructs 10.1.156 peer
└── constructs 10.1.156
```

Admittedly, I'm not an expert on package managers and dependency management, so I might be missing something fundamental here, but it looks to me like different parts of sst are using different versions of Constructs that have incompatible type definitions.

**Comment by JakeTompkins** [comment]
I apologize, I think I've figured it out

**Comment by berenddeboer** [comment]
I have exactly the same error @JakeTompkins, what did you do? With constructs 10.1.156 get an `Error [ERR_REQUIRE_ESM]: require() of ES Module error`, with constructs 10.2.28 I get the error above.

**Comment by jayair** [comment]
Make sure you stick to the versions that `sst version` prints out.

**Comment by pablote** [comment]
I have the same versions than `sst version` and it still fails

<img width="1434" alt="image" src="https://github.com/sst/sst/assets/2463995/6e962ee7-a957-407f-a79b-33c4e29ca416">

**Comment by jayair** [comment]
Open a thread in #help on Discord?
