### ISSUE TITLE
Live Lambda debugging not working after upgrade to SST 2

### ISSUE THREAD

**Issue by willjstevens** [serverless-stack/sst#2738]
Live Lambda debugging is not working in VSCode after upgrading to SST 2, most of the time. Rarely it works and catches one particular breakpoint, but none of the others. I can reproduce it nearly every time. 

A few things to point out:
- Everything runs smoothly in normal local (sst dev) running my application. It is the breakpoints that do not work
- I turned on verbose=true (the same output as debug.log) and nothing unusual. No errors when grepping for "error"
- I have an instinct this has something to do with the IOT implementation, perhaps permissions are causing it to fail silently. But I am unsure because I don't see anything unusual in the logs. 
- I followed the [upgrade guide](https://docs.sst.dev/upgrade-guide) with no issues, also ran a $ sst build, $sst deploy and still debugging is not working. 
- No, I am not on a VPN or behind a firewall - I am on my unrestricted home Internet
- Same issue with both nodejs1**6**.x and nodejs1**8**.x runtimes 

Environment
<pre>"devDependencies": {
    "constructs": "10.1.156",
    "sst": "2.3.7",
    "@tsconfig/node16": "^1.0.3",
    "aws-cdk-lib": "2.62.2",
    ...
  },</pre>
 
<pre>
    stacks(app) {
        app.setDefaultFunctionProps({
            runtime: "nodejs18.x"
        })
</pre>

I would really like to get this working, or revert back to SST version 1 to get live Lambda debugging working because it is a primary reason I use SST. 

Thanks for the nice development platform and DX. 

Discord cross reference: https://discord.com/channels/983865673656705025/1092981937653690439/1092981937653690439

**Comment by willjstevens** [comment]
Update: this has something to do with breakpoints not bound in VS Code. When I do an SST build sometimes it allows the breakpoints to catch, but then causes others to not work. 

When the breakpoint is a solid red dot in VS Code it is 'set' and source-mapped to the local compiled file. When it is a hallow clear dot it is not set and will not work.  There are various Github issues out there with very similar issues. 

I tried adding `"sourceMaps": true` to my launch.json but that did not work. 

I am now suspecting something in this launch executable file is not working right:

`"runtimeExecutable": "${workspaceRoot}/node_modules/.bin/sst",`

**Comment by jayair** [comment]
Yeah I saw this. Following up on Discord.

**Comment by rob3c** [comment]
Hi, any solution found for this? There wasn't any info in the linked discord thread either.

**Comment by jayair** [comment]
Hmm I don't think we've heard about this recently. Maybe post a new thread in #help on Discord?

**Comment by rob3c** [comment]
It turns out source maps needed to be enabled. The tutorial just didn't mention it and was written assuming it would just work.

**Comment by willjstevens** [comment]
Nice find and I am glad you got it to work with enabling source maps. I tried that above it and it did not work for me. 

Due to this and other issues with the V2 upgrade - I ended up abandoning SST. Too many open issues (presently 617 open), too little support, issues bouncing around between Git, Discord - things seem disorganized with no clarity of timeline or what exactly is being worked on and by who. There doesn't seem to be much focus on resolving the V2 issues but rather interest in moving onto rolling out Astro features and whatever is new at the moment. V2 should not have been released prematurely given so many open issues, unfortunately I don't think it was tested well. For my purposes, I cannot build a real product on this platform with this outlook. It may be more suitable for smaller, standalone apps. Note, my product is based on a large, cache-heavy and event-driven architecture which now orchestrates 7 separate CDK apps. It now works great having fully redesigned and reimplemented it on CDK.  

FWIW: I rebuild my entire multi-application AWS stack with pure CDK.  It took me some time (about 2 months, nights and weekends) but now I am loving it.  FYI, AWS basically developed the "constructs" and has a massive library of its own higher-level, [level 2 and level 3 constructs](https://docs.aws.amazon.com/cdk/v2/guide/constructs.html). I encourage you to take a look and consider that if you continue to struggle and don't want issues like this to be blockers. On AWS, the releases are stable, provide backwards compatibility and because their constructs *are* the constructs (e.g. underneath SST abstractions) the documentation provides the full details, all defaults, etc. Unfortunately V2 SST upgrade caused me over a month to troubleshoot, come to terms with lack of support, lack of stability, then another 1-2 months to rewrite everything in pure AWS CDK. Never going back. I came to realize that although well-intended, SST constructs were more of a veneer on top of already-built AWS constructs. What I do miss is the live, proxy debugger. However after providing a thorough write-up of the issue (e.g. this Git bug and another) there was no real support actually investigating to help provide a solution, but rather instruction to just duplicate it into Discord. I appreciate the original burst of productivity on SST but from my experience, I can't see SST as a suitable long-term platform to work on top of due to these reasons. 

Best of luck and hopefully this helps.

**Comment by rob3c** [comment]
Thanks @willjstevens for sharing your experience with giving SST a serious go on a real project! I was developing similar concerns about the large number of open issues, Discord redirects, etc. You've confirmed the support isn't there when the clock is ticking, and this may already be abandonware. Fortunately, I'm already very familiar with the CDK it's built on, so I can easily fall back to that alone if I need to.

I was really hoping to leverage the Live Lambda Debugging. Since SST is a superset of CDK, I figured I could stick to pure CDK constructs worst case except for the lambdas, and essentially use SST as a CDK wrapper if none of the other constructs were a good fit. I think this still may be possible, but we'll see. Your post has certainly given me pause.

FWIW, you mentioned enabling sourcemaps in the launch.json not working, whereas I enabled it in sst.config.ts as mentioned - buried, actually - in their docs nested in the advanced section. I would've thought it'd be stated more clearly given the prominence of the Live Lambda Debugging feature, but oh well. Maybe trying the config there would've worked for you.

**Comment by willjstevens** [comment]
I promptly posted issues in Discord when asked to do so - never received any help there. Just overcome by other incoming issues. Good luck.

**Comment by jayair** [comment]
Yeah sorry about that. If you run into something again, just mention me again on Discord and I'll get the team to take a look.

**Comment by closesimple-wl** [comment]
I have source maps enabled, the first Lambda invocation after launching the debugger never hits; the breakpoints are hollow.  After that invocation, the breakpoints become solid and subsequent invocations hit the breakpoints.

**Comment by jayair** [comment]
@closesimple-wl This doesn't seem related to the issue here. Open a new thread in #help in Discord?
