### ISSUE TITLE
Error: Stack SSTBootstrap is in the UPDATE_IN_PROGRESS state. It cannot be deployed.

### ISSUE THREAD

**Issue by iDVB** [serverless-stack/sst#2750]
It appears that whatever is supposed to be updating `SSTBootstrap` stack is doing so inline with regular user-stack pushes.
This is especially problematic when multiple user stacks are being deployed in parallel. In our case, in our monorepo. 
SST appears to be trying to update `SSTBootstrap` as part of that flow, but since we have 20+ `sst deploy` running in parallel, they are all trying to update `SSTBootstrap` at the same time.

Seems like an anti-pattern to update the SST Bootstrap stack `as part of the user stack deploy`. This feels like something that should instead be a completely isolated stack and update process like `sst update boilderplate`.

This way all updates are controlled by the users. Misaligned version of the `SSTBootstrap` should FAIL a user deploy IF there are breaking changes. 

```
Error: Stack SSTBootstrap is in the UPDATE_IN_PROGRESS state. It cannot be deployed.
```

**Comment by jayair** [comment]
@iDVB is this on #help on Discord?

**Comment by iDVB** [comment]
Hey @jayair !
Yup it is...

https://discord.com/channels/983865673656705025/1093533899424022568/1093533899424022568

**Comment by fwang** [comment]
Hey @iDVB. Just followed up on Discord.
