### ISSUE TITLE
Config Parameter/Secret binding is broken when setting ssmPrefix

### ISSUE THREAD

**Issue by gfmtim** [serverless-stack/sst#2751]
The SSM parameter names generated for the Parameter and Secret constructs come from this `PREFIX` helper: https://github.com/serverless-stack/sst/blob/master/packages/sst/src/config.ts#L256
which ignores the `ssmPrefix` option, so the stack uses the wrong key to create parameters and configure IAM permissions for them. The lambda gets an `SST_SSM_PREFIX` environment variable with the expected value, so at runtime it tries to read the parameter that *should* be there and throws an error.

**Comment by jayair** [comment]
Interesting. Can you post this on #help on Discord?

**Comment by fwang** [comment]
Fixed in v2.5.6
