### ISSUE TITLE
AWS_SESSION_TOKEN is also required when setting IAM credentials via env vars

### ISSUE THREAD

**Issue by davidrhoderick** [serverless-stack/sst#2773]
I tried to follow the documentation [here](https://docs.sst.dev/advanced/iam-credentials#loading-from-environment-variables) since we'll be deploying via CircleCI.  Unfortunately, I had to include an `AWS_SESSION_TOKEN` as well as the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` so I think the documentation should be updated.

**Comment by fwang** [comment]
Thanks @davidrhoderick!

Updated — https://github.com/serverless-stack/sst/commit/87352942d5795686d45eeaec038e13c15558ce0b
