### ISSUE TITLE
 Property 'public' does not exist on type 'typeof Bucket'

### ISSUE THREAD

**Issue by danhumphrey** [serverless-stack/sst#2790]
Hi,

I decided to jump in and try sst and I'm following the Use Astro with SST tutorial - it hasn't been a particularly quick start really 🤔

I've resolved a number of issues, but it's currently failing with the `public` property of `Bucket`. All code is copied from your tutorial here https://docs.sst.dev/start/astro, but for completeness, here's the code in `index.astro` (and other files - e.g. `delete.ts`):

`import {Bucket} from "sst/constructs";`

and the failing line:

```TypeScript
...
Bucket: Bucket.public.bucketName, // Property 'public' does not exist on type 'typeof Bucket'.
...
```

**Comment by danhumphrey** [comment]
Sorry, nevermind - I had a look at the files in the `examples` directory, they don't match your tutorial but I realised that I should be importing from `"sst/node/bucket"` instead

**Comment by zhifez** [comment]
Just an additional note for those using it in Next.JS, I also faced the same issue even though I imported correctly from `"sst/node/bucket"`, but the problem went away after I started running the local dev environment.
