### ISSUE TITLE
Could not find file for handler

### ISSUE THREAD

**Issue by joneslloyd** [serverless-stack/sst#2794]
I'm following the guide, specifically [this chapter](https://sst.dev/chapters/add-an-api-to-create-a-note.html) (Create a Note).

The only difference is that I'm using `.ts` files instead of .`js` files like the guide.

I've been sure to make the lambda file the same format as the example `lambda.ts` file that is included at the beginning of the project.

However, when I make the POST request to `/notes`, I get the following in my logs:
```
✖  Build failed packages/functions/src/lambda.handler
   Could not find file for handler "packages/functions/src/lambda.handler"
   ```
   
The contents of my `lambda.ts` are as follows:

```
import * as uuid from "uuid";
import AWS from "aws-sdk";
import { useBody, ApiHandler } from "sst/node/api";
import { Table } from "sst/node/table";

const dynamoDb = new AWS.DynamoDB.DocumentClient();

export const handler = ApiHandler(async (_evt) => {
  const body = useBody();
  // Request body is passed in as a JSON encoded string in 'body'
  const data = JSON.parse(body || "");

  const params = {
    TableName: Table.Notes.tableName,
    Item: {
      // The attributes of the item to be created
      userId: "123", // The id of the author
      noteId: uuid.v1(), // A unique uuid
      content: data.content, // Parsed from request body
      attachment: data.attachment, // Parsed from request body
      createdAt: Date.now(), // Current Unix timestamp
    },
  };

  try {
    await dynamoDb.put(params).promise();

    return {
      body: JSON.stringify(params.Item),
    };
  } catch (e: any) {
    return {
      statusCode: 500,
      body: JSON.stringify({ error: e.message }),
    };
  }
});
```

I've even tried running `npx sst remove APIStack` and then `npx sst dev` again, but this same error occurs.

Any idea why?

**Comment by joneslloyd** [comment]
**SOLVED**

Among other things, I wiped `node_modules` and reset all permissions on the top level dir recursively, which seems to have done the trick.

**Comment by kldeb** [comment]
Blowing away node_modules in the packages/functions dir worked for me.
