### ISSUE TITLE
partition error, please use dynamic partition

### ISSUE THREAD

**Issue by elonniu** [serverless-stack/sst#2797]
version: 2.5.7
partition: aws-cn
Partition "aws" is not valid for resource "arn:aws:s3:::sstbootstrap-cnnorth1d463b1fe-**". (Service: AmazonIdentityManagement

**Comment by jayair** [comment]
Hmmm can you post this on #help on Discord? I'll ask Frank to take a look.

**Comment by fwang** [comment]
Fixed in v2.7.2
