### ISSUE TITLE
API Gateway CloudWatch Log Role ARN updated with each new app deploy

### ISSUE THREAD

**Issue by ryancorvetti** [serverless-stack/sst#2799]
Multiple separate SST apps appear to fight over ownership of the account-level, regional CloudWatch log role ARN for API Gateway. I believe this to be bad practice and think that only a single app should have it set. Minimally, I think there should be a way to disable it by default, so that developers can decide explicitly which CloudFormation stack should manage this configuration setting per account/region.

**Comment by jayair** [comment]
Saw this on Discord. Let's look at it there!

**Comment by ryancorvetti** [comment]
Upon further inspection, this appears to be default behavior of CDK itself.  https://github.com/aws/aws-cdk/issues/10878

I will follow their suggested approach of disabling via `restApi.cloudWatchRole = false` and setting up one time explicitly in a separate "shared infrastructure" app using `CfnAccount` construct.
