### ISSUE TITLE
Cloudfront returns {"message":null} for all page Next.js 13 paths

### ISSUE THREAD

**Issue by davisuga** [serverless-stack/sst#2808]
When I try static asset paths it works, like /robots.txt or /_next/static/chunks/pages/_app-42c2ab404d96cb15.j
It server lambda invocations but no useful logs are produced.
I use Next.js 13.1.6 and SST 2.5.3

The server lambda outputs the following logs:

```

2023-04-25T08:28:50.340-03:00 | INIT_START Runtime Version: nodejs:18.v6 Runtime Version ARN: arn:aws:lambda:us-east-1::runtime:813a1c9d8f27c16e2f3288da6255eac7867411c306ae9cf76498bb320eddded2
-- | --
  | 2023-04-25T08:28:50.975-03:00 | 2023-04-25T11:28:50.975Z undefined INFO info - Loaded env from /var/task/.env
  | 2023-04-25T08:28:51.921-03:00 | START RequestId: e15cc581-1a97-42af-81a2-43583462bf7d Version: $LATEST
  | 2023-04-25T08:28:52.871-03:00 | END RequestId: e15cc581-1a97-42af-81a2-43583462bf7d

```

**Comment by fwang** [comment]
Hi @davisuga, can you create a minimal repo that I can use to reproduce on my end?

**Comment by davisuga** [comment]
I tried to deploy the same app to Vercel and I discovered by looking at the logs that the middleware were throwing an exception because some env variable was missing. It logs nothing on cloudwatch when I tried SST.
