### ISSUE TITLE
"RequestContext" context was not provided

### ISSUE THREAD

**Issue by joneslloyd** [serverless-stack/sst#2815]
I'm following the guide, specifically [this chapter](https://sst.dev/chapters/add-a-create-note-api.html#refactor-our-code) (Refactor our Code).

The only difference is that I'm using .ts files instead of .js files like the guide.

I've been sure to make the `handler.ts` file the same as that of the guide, but with TypeScript types:
[Here](https://gist.github.com/joneslloyd/f7a0cf45948834875261593d096f23b4)

However, when I make the POST request to /notes to create a new one, I get the following error:
`"RequestContext" context was not provided.`

I've tried changing the types of the function itself, and the `lambda` parameter, in `handler.ts`, but this error keeps appearing.

I get the same error when I try to GET an existing note too (so it's not just on POST).

Does anybody have any ideas?

**Comment by joneslloyd** [comment]
Okay, so the issue was using the `useBody` and `usePathParams` hooks.

In `create.ts`, this does not work:
```
export const main = handler(async (_evt, _ctx) => {
  const body = useBody();
  // Request body is passed in as a JSON encoded string in 'body'
  const data = JSON.parse(body || "");
  const params = {
    TableName: Table.Notes.tableName,
    Item: {
      // The attributes of the item to be created
      userId: "123", // The id of the author
      noteId: uuid.v1(), // A unique uuid
      content: data.content, // Parsed from request body
      attachment: data.attachment, // Parsed from request body
      createdAt: Date.now(), // Current Unix timestamp
    },
  };

  await dynamoDb.put(params);

  return params.Item;
});
```

Whereas this does:

```
export const main = handler(async (_evt, _ctx) => {
  const body = _evt?.body || "";
  // Request body is passed in as a JSON encoded string in 'body'
  const data = JSON.parse(body || "");
  const params = {
    TableName: Table.Notes.tableName,
    Item: {
      // The attributes of the item to be created
      userId: "123", // The id of the author
      noteId: uuid.v1(), // A unique uuid
      content: data.content, // Parsed from request body
      attachment: data.attachment, // Parsed from request body
      createdAt: Date.now(), // Current Unix timestamp
    },
  };

  await dynamoDb.put(params);

  return params.Item;
});
```

(And the use of `usePathParams` in `get.ts` presents a similar problem)

**Comment by jayair** [comment]
Hmm I need to look at this in depth but we'll be working on a TS version soon.

**Comment by joneslloyd** [comment]
Thanks!

Shall I close this for now?

**Comment by jayair** [comment]
Yeah go for it.

**Comment by MaHdix9** [comment]
Bruh who are u

بتاريخ الجمعة، 28 أبريل 2023، جاء من Jay ***@***.***>:
