### ISSUE TITLE
NextjsSite does not support webp or avif NextJS optimized images due to omitted Accept header

### ISSUE THREAD

**Issue by richardcornelissen** [serverless-stack/sst#2820]
NextJS used WebP by default and supports AVIF when enabled in `next.config.js` (see [here](https://nextjs.org/docs/api-reference/next/image#acceptable-formats)).
To do so, it uses the `Accept` request header to determine supported image formats for the browser.

However, the NextJSSite construct uses a cache policy that does not send any headers to the image origin by default (see https://github.com/serverless-stack/sst/blob/v2.7.2/packages/sst/src/constructs/NextjsSite.ts#L224).

**Comment by jayair** [comment]
Can you post this on #open-next on Discord? Feel free to tag me @Jay.

**Comment by richardcornelissen** [comment]
Fixed with commit https://github.com/serverless-stack/sst/commit/ac7622928998c438f4645f38bef6a038b309b061
