### ISSUE TITLE
Feature Request: Allow NextJSSite to accept Header Response Policy

### ISSUE THREAD

**Issue by derekmurawsky** [serverless-stack/sst#2895]
Per [this conversation in Discord](https://discord.com/channels/983865673656705025/1108751429956550697/1108751429956550697), I am opening a feature request to allow the NextJSSite construct to accept Response Header Policy objects to be attached to the CloudFront Distribution Behaviors that are currently generated. 

## Feature Request

As a security engineer, I want to make sure all hosted assets have certain security headers, like `Strict-Transport-Security`. [The current NextJSSite construct](https://github.com/serverless-stack/sst/blob/90c5f64323466f0f1cf3082aadbf925bf6205ccf/packages/sst/src/constructs/NextjsSite.ts#L325) does not have a way to set the [`responseHeadersPolicy`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudfront.BehaviorOptions.html#responseheaderspolicy) property on the `_next/image*` or `_next/*` path behaviors. Because of limitations in CDK, there is no way to alter this configuration after the distribution has been instantiated.

I would like a way to set a `responseHeadersPolicy` for each behavior that is created by the NextJSSite construct. 

## Things I've looked into

-  I can set these in my [next app natively](https://nextjs.org/docs/pages/api-reference/next-config-js/headers) for any path where the lambda function is invoked, however, the function is not, and can not, be invoked on the other static asset paths
- I can set this policy for the `default` behavior, but that behavior is *not* inherited by other behaviors. 
- I may be able to set s3 metadata on the files in S3, but that is clunky and inelegant
- This cannot be done via aspects as far as I know because behaviors are not nodes, and aspects must work on a full node
- This cannot be done by the cache policy, as that just handles headers that already exist. I want to set the headers explicitly.

**Comment by derekmurawsky** [comment]
# Spec

All optional policy variables will be a simple string that is the ResponseHeaderPolicyID. In CDK land, this can easily be obtained by creating the policy with the [ResponseHeadersPolicy construct](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudfront.ResponseHeadersPolicy.html) or [ResponseHeadersPolicy.fromResponseHeadersPolicyId()](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_cloudfront.ResponseHeadersPolicy.html#static-fromwbrresponsewbrheaderswbrpolicywbridscope-id-responseheaderspolicyid)

- [ ] Extend NextjsSiteProps to include an optional responseHeadersPolicies object. 
   - [ ] Optional "serverBehaviorResponseHeaderPolicy" to be applied to the buildServerBehaviorForRegional and buildServerBehaviorForEdge functions
   - [ ] Optional "imageBehaviorHeaderPolicy" to be applied to the buildImageBehavior function
   - [ ] Optional "staticFileBehaviorHeaderPolicy" to be applied to the buildStaticFileBehavior function
   - [ ] Optional "defaultBehaviorHeaderPolicy" to be applied to the buildDefaultNextjsBehaviorForRegional and buildDefaultNextjsBehaviorForEdge functions

**Comment by jayair** [comment]
Related Discord thread https://discord.com/channels/983865673656705025/1108751429956550697/1108751429956550697

**Comment by fwang** [comment]
Added in v2.10.2

**Comment by derekmurawsky** [comment]
Thank you kindly! We're looking to migrate over shortly now that this feature is in. Much appreciated!
