### ISSUE TITLE
Allow Support of PostgreSQL v11.16

### ISSUE THREAD

**Issue by GMoon777** [serverless-stack/sst#2896]
AWS auto migrated all of our postgres 10.14 RDS instances to 11.16, which means our Database stacks are stuck - we can't upgrade to the currently supported 11.13 because they have already been updated to 11.16, and can no longer roll back to 10.14 because that is EOL

Added the follow code to a PR here - https://github.com/serverless-stack/sst/pull/2897 

It's my first time forking a repo I hope this is all good.

In file RDS.ts
sst/blob/master/packages/sst/src/constructs/RDS.ts

Line 31:
  engine: "mysql5.6" | "mysql5.7" | "postgresql10.14" | "postgresql11.13" | "postgresql11.16";

Line 409:
else if (engine === "postgresql11.16") {
            return rds.DatabaseClusterEngine.auroraPostgres({
                version: rds.AuroraPostgresEngineVersion.VER_11_16,
            });
        }

**Comment by jayair** [comment]
Yeah let me ask the team to review this quick.

**Comment by parmus** [comment]
This is very much affecting us as AWS doesn't seem to provide a downgrade path from 11.16 to 11.13. So anyone who have been auto-upgraded like us is currently stuck with a RDS setup, which can't be managed using SST.  This is currently the case for all our environments.

**Comment by GMoon777** [comment]
@thdxr @jayair any update on this?.  The automatic upgrade by AWS has caused major fallout and we are holding onto hope that this will be resolved soon! 🥇 🙏  🥳

**Comment by jayair** [comment]
Yeah let me double check.

**Comment by thdxr** [comment]
this is fixed in latest release
