### ISSUE TITLE
SST console stuck with old metadata

### ISSUE THREAD

**Issue by chrisandrewcl** [serverless-stack/sst#2900]
http://console.set.dev is getting stuck with old metadata. While tracking down what was happening, I noticed in the browser devtools that requests¹ to get stack metadata were using the disk cache. Disabling the browser cache fixed the problem.

Not sure if this is intended behavior, or if I got something wrong, but it would be nice to prevent metadata caching, or at least warn about this behavior in the docs.

¹ E.g. http://localhost:13557/proxy/https://sstbootstrap-....s3.sa-east-1.amazonaws.com/stackMetadata/app..../stage..../stack.....json?x-id=GetObject

**Comment by tobz1000** [comment]
Related (dupe of?): #2248

**Comment by chrisandrewcl** [comment]
You are right! :facepalm:
