### ISSUE TITLE
Enhanced fan-out for Kinesis streams?

### ISSUE THREAD

**Issue by airandfingers** [serverless-stack/sst#2920]
Hi, I'm looking to set up [Enhanced Fan-Out](https://docs.aws.amazon.com/streams/latest/dev/enhanced-consumers.html) for some Lambda stream consumers we're creating with SST.

Per the [docs](https://docs.aws.amazon.com/lambda/latest/dg/with-kinesis.html#services-kinesis-configure), it looks like I should be able to specify a consumer ARN (as returned to a [RegisterStreamConsumer](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_RegisterStreamConsumer.html) command send with the stream's ARN).

Here's what this looks like in the Console UI:

<img width="817" alt="image" src="https://github.com/serverless-stack/sst/assets/1088051/4cfead01-9619-49b3-84e9-4ad5a536305d">

<br />
<br />

However, `aws-cdk-lib/aws-lambda-event-sources:KinesisEventSource` (which we're creating and passing to our `Function` constructor to set up our Lambda as a stream consumer) doesn't take any arguments that look like this consumer ARN.. Is there another way to specify this subscription that _does_ take such a consumer ARN?

Side note: [other docs](https://docs.aws.amazon.com/streams/latest/dev/building-enhanced-consumers-api.html) show how to manually subscribe to a stream by sending [SubscribeToShard](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_SubscribeToShard.html) commands every 5 minutes with the consumer ARN and a shard ID. I struggle to see how this could be used to trigger a Lambda; it seems to be independent of Lambda triggers, and intended for long-lived processes that need to consume a stream.

**Comment by jayair** [comment]
Can you post this on #help on Discord and we'll take a look?

**Comment by airandfingers** [comment]
Thanks @jayair, my teammates figured this out based on [this example](https://gitlab.com/rrhodes/kinesis-enhanced-fan-out/-/blob/master/lib/kinesis-enhanced-fan-out-stack.ts) so we should be good to go!

In case anyone comes across this, I'll note that `EventSourceMapping` seems to take our SST `Function` construct for its `target` argument, so this CDK approach works without much fuss.
