### ISSUE TITLE
No stacks found

### ISSUE THREAD

**Issue by BelphegorPrime** [serverless-stack/sst#2947]
when running `npx sst build --stage dev --verbose --region us-east-1 --to .sst/cdk.out`

with sst version `2.10.4` there are the right amount of stacks found
`Built: 2 stacks to .sst/cdk.out`

with sst version `2.11.7` there are no stacks found
`Built: 0 stack to .sst/cdk.out`

Is there some undocumented migration needed?
Is it a bug?

**Comment by jayair** [comment]
Can you post this on #help on Discord?
