### ISSUE TITLE
No loader is configured for ".node" files

### ISSUE THREAD

**Issue by gksudhanshu** [serverless-stack/sst#2953]
Hey, I am trying to add "ssh2-sftp-client" to send files to sftp but this package throws below error in sst app but it is working fine with js node script. It looks like I need to add loader in build process but not sure where. Could you please help me?
node version: v16.13.0
 

here is the sample code:  

let Client = require('ssh2-sftp-client');
let sftp = new Client();

sftp.connect({
  host: '127.0.0.1',
  port: '8080',
  username: 'username',
  password: '******'
}).then(() => {
  return sftp.list('/pathname');
}).then(data => {
  console.log(data, 'the data info');
}).catch(err => {
  console.log(err, 'catch error');
});

X [ERROR] No loader is configured for ".node" files: node_modules/cpu-features/build/Release/cpufeatures.node

    node_modules/cpu-features/lib/index.js:3:24:
      3 │ const binding = require('../build/Release/cpufeatures.node');
        ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

X [ERROR] No loader is configured for ".node" files: node_modules/ssh2/lib/protocol/crypto/build/Release/sshcrypto.node

    node_modules/ssh2/lib/protocol/crypto.js:30:20:
      30 │   binding = require('./crypto/build/Release/sshcrypto.node');
         ╵                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Error: There was a problem transpiling the Lambda handler: Error: Build failed with 2 errors:
node_modules/cpu-features/lib/index.js:3:24: ERROR: No loader is configured for ".node" files: node_modules/cpu-features/build/Release/cpufeatures.node    
node_modules/ssh2/lib/protocol/crypto.js:30:20: ERROR: No loader is configured for ".node" files: node_modules/ssh2/lib/protocol/crypto/build/Release/sshcrypto.node
    at Object.bundle (file:///C:/Users/gopals2/OneDrive%20-%20kochind.com/Desktop/dev/APP_CONSULTING/FSM/new-dev/csfoutbound_getpaid/node_modules/@serverless-stack/core/dist/runtime/handler/node.js:175:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by jayair** [comment]
This probably needs to be excluded from the rebuild bundle. https://docs.sst.dev/constructs/Function#install

**Comment by gksudhanshu** [comment]
Thanks! It helped me to fix this issue.
