### ISSUE TITLE
site URL as environment variables in NextSite

### ISSUE THREAD

**Issue by adikari** [serverless-stack/sst#2987]
It would be nice to have the Site Url and Custom Domain Url, if available set to the environment of the lambda function. 

I want to use the URL of the cloudfront in my lambda function. Currently, I am doing a deployment first which gives me the URL. Then I do another deployment by adding it to the environment.

Is there any better way to do it currently? If no, it might be good to set the URL in the lambda function.

something like

NEXT_PUBLIC_SITE_URL, NEXT_PUBLIC_CUSTOM_DOMAIN_URL

**Comment by jayair** [comment]
This is interesting. I see somebody referenced this issue in #help on Discord. We'll respond there but to clarify, you want to access this in the server function right?

**Comment by nevolgograd** [comment]
@jayair just for general understanding, in serverless when I want to access dynamic value in my stack (property of the created resource like a dynamo table name or cognito client id or cloudfront url in this case) I usually use `!Ref` CF function, or `!ImportValue` if I need it in the different stack.

Do you support those?

**Comment by jayair** [comment]
Responded on Discord.

**Comment by adikari** [comment]
I am not on discord. Why not reply on GitHub and resolve it, before closing the issue?

I think it's reasonable to expect to have the environment variables exposed both to the server and client.

**Comment by jayair** [comment]
We don't use GH issues sadly.

About the issue itself, we probably won't introduce extra environment variables. I think it'll make more sense to make it available through the SST Node client.

**Comment by adikari** [comment]
That would be fine too. Just need some way to get the URL. I did join discord. Where do we post the request?

**Comment by nevolgograd** [comment]
@adikari https://discord.com/channels/983865673656705025/1115713625403969636/1115713625403969636
