### ISSUE TITLE
[NextJsSite] Revalidation function forbidden by CloudFront WAF

### ISSUE THREAD

**Issue by ealain** [serverless-stack/sst#3016]
# Context

I am using a WAF on CloudFront to enforce IP whitelisting.

# Issue

The revalidation function that provides the ISR feature of Next.js is forbidden by the CloudFront WAF.

# Solution

In order to control the function IP, the function needs to be provisioned in a VPC with a static IP. So adding a prop to specify the function's VPC would help.

- [ ] feat: add `revalidation.vpc` prop to `NextJsSiteProps`
- [ ] feat: add `vpc` to the revalidation function in `createRevalidation`

I can work on a PR if this speccing looks good.

**Comment by jayair** [comment]
Not sure if you posted this in Discord. Can you put it in #help and I'll ask the team to take a quick look at the spec.

**Comment by fwang** [comment]
Released in 2.16.4
