### ISSUE TITLE
Emit error rather than silent failure to install dependencies

### ISSUE THREAD

**Issue by ipatka** [serverless-stack/sst#3021]
https://github.com/serverless-stack/sst/blob/d615080013d8fc09d1bfc93bfe53284866d71c5f/packages/sst/src/runtime/handlers/node.ts#L233

When install fails due to any reason the script appears to succeed but it fails to package node_modules in the lambda. Instead it should catch the failure and block the build

Ex here is a fsevents package which fails to install on Ubuntu. If fsevents is included in sstconfig, it will fail to build on ubuntu based CI (like GH actions), leading to broken lambdas deployed to production
![image](https://github.com/serverless-stack/sst/assets/4401444/adb0d228-3a83-4d16-b12b-f4753db827a0)

**Comment by jayair** [comment]
Oh interesting. Good catch. Would appreciate a PR!

**Comment by ipatka** [comment]
> Oh interesting. Good catch. Would appreciate a PR!

will give it a try this week!

**Comment by ipatka** [comment]
@jayair Added a fix with test cases in the PR above

**Comment by fwang** [comment]
Released in 2.17.0
