### ISSUE TITLE
Basic auth for nextjs 13 and sst not working

### ISSUE THREAD

**Issue by suil** [serverless-stack/sst#3039]
trying to get basic auth to work with nextjs 13 and sst. but it still fails...

i was able to get it work locally by following this: https://rajdeep-das.medium.com/next-js-app-dir-and-route-handlers-http-basic-auth-e0d0edb1851

then i did this
```
    app.stack(function Site({ stack }: any) {
      const site = new NextjsSite(stack, 'stack', {
        customDomain: {
          domainName: '...com',
          cdk: {
            hostedZone: HostedZone.fromHostedZoneAttributes(stack, 'Zone', {
              hostedZoneId: 'Z0...',
              zoneName: '...',
            }),
            certificate: Certificate.fromCertificateArn(
              stack,
              'Cert',
              'arn:aws:acm:us-east-1:...'
            ),
          },
        },
        cdk: {
          serverCachePolicy: new CachePolicy(
            stack,
            'ServerCacheWithAllowedHeader',
            {
              queryStringBehavior: CacheQueryStringBehavior.all(),
              headerBehavior: CacheHeaderBehavior.allowList(
                'accept',
                'rsc',
                'next-router-prefetch',
                'next-router-state-tree',
                'authorization'
              ),
              cookieBehavior: CacheCookieBehavior.all(),
              defaultTtl: Duration.days(0),
              maxTtl: Duration.days(365),
              minTtl: Duration.days(0),
              enableAcceptEncodingBrotli: true,
              enableAcceptEncodingGzip: true,
            }
          ),
        },
      });
```

it's suppose to work. but the basic auth usename/password alert box did not pop up

**Comment by khuezy** [comment]
I could have sworn this was working for me in the past... I could be misremembering it. But the issue now is that APIGateway remaps the `WWW-Authenticate` headers to `x-amzn-remapped-www-authenticate`. Could have been some changes to NextjsSite since I've implemented basic auth.

One work around I think could work is to add a VIEWER_REQUEST lambda function to check for authentication and return immediately.

**Comment by fwang** [comment]
shared a solution on Discord — https://discord.com/channels/983865673656705025/1123310249508601917/1123718579720814684
