### ISSUE TITLE
Need to cancel running Jobs

### ISSUE THREAD

**Issue by svaterlaus** [serverless-stack/sst#3040]
Hi, I'm really enjoying using this library so far. Thanks for working on it.

I need to be able to cancel a running Job from within some Lambda code. I considered the use of the `@aws-sdk/client-codebuild` `StopBuildCommand`, but I would need the id for the active build and I don't see a way to get that via the `Job['job-name'].run()` method. I looked over the source code as well and don't see any obvious solution for that.

Is there a way to get the build id or a different way to go about cancelling an active Job?

**Comment by svaterlaus** [comment]
Or possibly a way to attach some metadata to the build when it's run so I can identify it after listing the running builds and get the id that way. :thinking:

**Comment by jayair** [comment]
Yeah this seems useful. Can you open a thread in #help on Discord? And we'll take a look.

**Comment by svaterlaus** [comment]
Closing this thanks to @fwang , works great! Thanks!

**Comment by Dzhuneyt** [comment]
@svaterlaus what was the solution though?

**Comment by svaterlaus** [comment]
@Dzhuneyt, just update SST to v2.21 or later. Now you can get the `jobId` from the Job `run` method, then use the new `cancel` method--should be there in the docs.
