### ISSUE TITLE
S3 uploader doesn't set header metadata correctly

### ISSUE THREAD

**Issue by juranki** [serverless-stack/sst#3042]
I deployed a NextJS site with sst@2.17.2, but noticed that cache-control header was not set on responses served from assets bucket. Header metadata is missing from S3 objects.

I see from the logs that `file_options' carries cache settings, but they are not applied to objects.

As a workaround I added `--cache-control` param to `s3 sync` command [here](https://github.com/serverless-stack/sst/blob/master/packages/sst/support/base-site-custom-resource/s3-upload.py#L79-L81):
![image](https://github.com/serverless-stack/sst/assets/6607/c0c41e7b-2f26-4060-b1c5-b4e03c0de04c)

It works, but probably is not desirable because more fine grained settings from `file_options` are lost.

**Comment by jayair** [comment]
Do you mind opening a thread in #help on Discord with this? We'll look into this.

**Comment by yhatt** [comment]
I also have met a same issue and opened a thread on Discord. My workaround is overloading `createS3AssetFileOptions()` in the extended class from `NextjsSite`, to add post-process for prepending `_assets/` to the include path.

```javascript
class CustomNextjsSite extends NextjsSite {
  createS3AssetFileOptions() {
    const fileOptions = super.createS3AssetFileOptions();

    return fileOptions.map((fileOption) => ({
      ...fileOption,
      include: `${this.buildConfig.clientBuildS3KeyPrefix}/${fileOption.include}`
    }));
  }
}
```

**Comment by khuezy** [comment]
@fwang is this just a matter of added the prefix to the `include` at https://github.com/serverless-stack/sst/blob/master/packages/sst/src/constructs/SsrSite.ts#L702

eg
```
if (this.buildConfig.clientBuildS3KeyPrefix) item = `${this.buildConfig.clientBuildS3KeyPrefix}/${item}`
```
```

**Comment by fwang** [comment]
Thanks @khuezy. Will be in the next release.

**Comment by fwang** [comment]
Released in 2.18.0

**Comment by yhatt** [comment]
@khuezy Hey, thanks for your great contribution. I tried deploying Next.js with the updated sst and `NextjsSite` class. Now Cache-Control for public resources that located in `public` directory of Next.js project are set correctly.

However, Cache-Control for generated static resources located in `_assets/_next/static` is still not setting. So static resources used by Next.js are still not optimized delivering.

```
['--exclude', '*', '--include', '_assets/BUILD_ID', '--cache-control', 'public,max-age=0,s-maxage=31536000,must-revalidate']
| aws s3 cp /tmp/tmp519l6it_/contents s3://xxxxxxxxxxxxxxxx --recursive --exclude * --include _assets/BUILD_ID --cache-control public,max-age=0,s-maxage=31536000,must-revalidate
Completed 21 Bytes/21 Bytes (194 Bytes/s) with 1 file(s) remaining upload: ../../tmp/tmp519l6it_/contents/_assets/BUILD_ID to s3://xxxxxxxxxxxxxxxx/_assets/BUILD_ID

['--exclude', '*', '--include', '_next/*', '--cache-control', 'public,max-age=31536000,immutable']
| aws s3 cp /tmp/tmp519l6it_/contents s3://xxxxxxxxxxxxxxxx --recursive --exclude * --include _next/* --cache-control public,max-age=31536000,immutable
### Ignored

['--exclude', '*', '--include', '_assets/favicon.ico', '--cache-control', 'public,max-age=0,s-maxage=31536000,must-revalidate']
....
```

Setting Cache-control for `_next/*` is ignored because actually located assets at `_assets/next/*`. I think should require updating `include` for versioned files too: https://github.com/serverless-stack/sst/blob/28ef6b2f80ceb1f7bb983080003bd812c74fe086/packages/sst/src/constructs/SsrSite.ts#L702

```diff
-          include: `${this.buildConfig.clientBuildVersionedSubDir}/*`,
+          include: path.posix.join(
+            this.buildConfig.clientBuildS3KeyPrefix ?? "",
+            this.buildConfig.clientBuildVersionedSubDir,
+            '*'
+          ),
```

And following custom class is updated workaround for sst v1.28.0:

```javascript
class CustomNextjsSite extends NextjsSite {
  createS3AssetFileOptions() {
    const fileOptions = super.createS3AssetFileOptions();

    return fileOptions.map((fileOption) => {
      const newFileOption = { ...fileOption };

      // Avoid duplicated prefixes
      if (
        this.buildConfig.clientBuildS3KeyPrefix &&
        !fileOption.include.startsWith(
          `${this.buildConfig.clientBuildS3KeyPrefix}/`
        )
      ) {
        newFileOption.include = `${this.buildConfig.clientBuildS3KeyPrefix}/${fileOption.include}`;
      }

      return newFileOption;
    });
  }
}
```

**Comment by khuezy** [comment]
Nice catch @yhatt! Will look soon.

**Comment by khuezy** [comment]
@fwang @yhatt ^ fixes the versioned subdir
