### ISSUE TITLE
Cognito authorization to an openSearch domain in gov-cloud is broken

### ISSUE THREAD

**Issue by djesurum** [serverless-stack/sst#3121]
When the region starts with "us-gov" then inside constructs/Cognito.js::CreateAuthRole(identityPool)
the "cognito-identity.amazonaws.com" Strings need to instead be "cognito-identity-us-gov.amazonaws.com".
i.e.,
```ts
        const role = new iam.Role(this, "IdentityPoolAuthRole", {
            assumedBy: new iam.FederatedPrincipal("cognito-identity-us-gov.amazonaws.com", {
                StringEquals: {
                    "cognito-identity-us-gov.amazonaws.com:aud": identityPool.ref,
                }, 
                "ForAnyValue:StringLike": {
                    "cognito-identity-us-gov.amazonaws.com:amr": "authenticated",
                },
            }, "sts:AssumeRoleWithWebIdentity"),
        }); 
```
This logic should probably be region specific,
and should also be applied to the createUnauthRole(identityPool) as-well.

**Comment by jayair** [comment]
Related Discord thread https://discord.com/channels/983865673656705025/1129072159684300810/1129072159684300810

**Comment by fwang** [comment]
Fixed here https://github.com/serverless-stack/sst/commit/8612a54f97c3fb9983c13c8f8d05a55b8f176a12

Will be in the next release.
