### ISSUE TITLE
Next.js 13 - 502 Bad Gatway

### ISSUE THREAD

**Issue by paullotz** [serverless-stack/sst#3136]
Hello, I have set up my SST config according to the docs for Next.js. The deployment finishes without any errors but once trying to open the page in the browser, I am getting a 502 bad gateway error + favicon Cross Origin Policy Error (if that matters). Site is not reachable shows no content. The next.js app is fairly small, only using one api and has no off the standards implementations

```
export default {
  config(_input) {
    return {
      name: "weather-app",
      region: "eu-central-1",
    };
  },
  stacks(app) {
    app.stack(function Site({ stack }) {
      const site = new NextjsSite(stack, "site", {
        environment: {
          API_KEY: process.env.API_KEY ? process.env.API_KEY : "",
        },
        cdk: {
          server: {
            logRetention: RetentionDays.ONE_MONTH,
          },
        },
        memorySize: "1024 MB",
      });

      stack.addOutputs({
        SiteUrl: site.url,
      });
    });
  },
} satisfies SSTConfig;
```

Field | Value
-- | --
@message | 2023-07-18T15:58:23.513Z	undefined	ERROR	Failed to override Next.js require hooks. Error: Cannot find module '/var/task/node_modules/react/jsx-runtime.js'    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1096:15)    at finalizeEsmResolution (node:internal/modules/cjs/loader:1089:15)    at resolveExports (node:internal/modules/cjs/loader:565:14)    at Module._findPath (node:internal/modules/cjs/loader:634:31)    at Module._resolveFilename (node:internal/modules/cjs/loader:1061:27)    at /var/task/node_modules/next/dist/server/require-hook.js:113:36    at Function.resolve (node:internal/modules/cjs/helpers:116:19)    at U7 (file:///var/task/index.mjs:34:7367)    at oM (file:///var/task/index.mjs:34:6984)    at file:///var/task/index.mjs:34:10398 {  code: 'MODULE_NOT_FOUND',  path: '/var/task/node_modules/react/package.json'}
@timestamp | 1689695903513
code | MODULE_NOT_FOUND
path | /var/task/node_modules/react/package.json

running the app locally with
`npm run build`
and
`npm run start`
works perfectly

**Comment by jayair** [comment]
Can you post this on #help on Discord?

**Comment by paullotz** [comment]
Resolved. Downgraded Next.js version to 13.4.9.
