### ISSUE TITLE
StaticSite fails: CustomResourceHandlerService is not authorized to perform cloudfront:CreateInvalidation

### ISSUE THREAD

**Issue by sintexx** [serverless-stack/sst#3141]
_Affected Version:_ 2.22.2

_Description:_

Creating a minimal example with a [StaticSite](https://docs.sst.dev/constructs/StaticSite#creating-a-plain-html-site) fails on the initial deploy because the first invalidation for cloudfront can not be created.

_How to reproduce:_

Create a new SST-Application with a simple static site:

```
const site = new StaticSite(stack, "frontend", {
    path: "staticSite",
  });

  stack.addOutputs({
    URL: site.url,
  });
```

Create the folder "staticSite" and put an index.html in it.

Run `sst deploy`

_Detailed description:_

The S3-Bucket, CloudFront and ResourceHandlers are all successfully created, but when the CustomResourceHandlerService tries to create the CloudFrontInvalidator it fails with insufficient permissions:

`Received response status [FAILED] from custom resource. Message returned: User: arn:aws:sts::***:assumed-role/dev-checkStaticSite-API-CustomResourceHandlerSer-MKZUO8ROT9BC/dev-checkStaticSite-API-CustomResourceHandlerE8F-i2PNzRDYJ6yT is not authorized to perform: cloudfront:CreateInvalidation on resource: arn:aws:cloudfront::***:distribution/E1PDXUY88FA753 because no identity-based policy allows the cloudfront:CreateInvalidation action`

In the generated CloudFormation-Template it looks like a policy with the correct cloudfront permissions is created and attached to the lambda.

The user that is used to run the sst command has AdminAccess.

**Comment by bauer01** [comment]
see https://discord.com/channels/983865673656705025/1129090346874322985

**Comment by sintexx** [comment]
It is working again since this morning and it looks like this was an AWS problem specific to eu-central-1 and not specific to sst.
