### ISSUE TITLE
How did sst support java lambdas?

### ISSUE THREAD

**Issue by ljd1991** [serverless-stack/sst#3148]
I am new to sst and I am trying to use sst to support developing lambdas using java.
I assume that maybe after I configure a jar package like "lambda.jar" and a handler location in some file, and run "npm run dev" locally, then sst will forwards cloud events like APIGateway events to local environment to call lambda I provided in lambda.jar?

But I do not really know how to implement that, is there any guidelines or examples I can refer to?

**Comment by jayair** [comment]
Here are the Java docs https://docs.sst.dev/constructs/Function#configuring-java-runtime
