### ISSUE TITLE
Discrepancy between documentation and implementation regarding typecheck

### ISSUE THREAD

**Issue by tharakadesilva** [serverless-stack/sst#3166]
https://docs.sst.dev/learn/project-structure#scripts says:

> typecheck: Run typecheck for the entire project. ...

However, [this commit](https://github.com/serverless-stack/sst/commit/3db05a0e9b7a116b1285d10cc142bea496a47fa5) is removing typecheck from running on packages.

If this commit is correct, then the docs need to be updated or vice-versa. If it is the latter, what would the recommended way be to run typechecking on the entire project?

**Comment by kevintechie** [comment]
The docs are frustratingly out of date. This makes it very difficult for a person that is new to SST to get up to speed.

**Comment by jayair** [comment]
Sorry about that. Updating that tutorial is a little bit of work. So I appreciate you pointing this out. Let me test this.

**Comment by jayair** [comment]
Just checked, yeah the tutorial needs to be changed.

**Comment by jayair** [comment]
Updated it.

**Comment by tharakadesilva** [comment]
Hi @jayair, thank you! As a part of CI, if I want to run `typecheck` on the entire project, how can I do this?

**Comment by jayair** [comment]
Since the separate packages run it on their own, you can either run a script to do it or use something like https://pnpm.io/cli/recursive
