### ISSUE TITLE
Add notifications to existing S3 Bucket

### ISSUE THREAD

**Issue by fwang** [serverless-stack/sst#338]
Currently waiting for CDK to add support for it.

The initial implementation is done, waiting to be merged - https://github.com/aws/aws-cdk/issues/2004

**Comment by michaelbrewer** [comment]
I am working on the PR: https://github.com/aws/aws-cdk/pull/11773 I am just not sure it will get merged or not

**Comment by fwang** [comment]
@michaelbrewer We've got a couple of folks in the community that are been waiting for this ;)

Thanks for the hard work! Really appreciate it!

**Comment by michaelbrewer** [comment]
@fwang  - this should be unblocked now

**Comment by fwang** [comment]
Hey @michaelbrewer, this is longgg overdue... finally added support for this in v1.14.4
