### ISSUE TITLE
Function: Better error message for copyFiles option

### ISSUE THREAD

**Issue by jayair** [serverless-stack/sst#472]
If you pass in an object instead of an array it fails. We should show an error message saying that we were expecting an array.

<img width="559" alt="Screen Shot 2021-06-18 at 5 49 30 PM" src="https://user-images.githubusercontent.com/53023/122619122-b741a280-d05d-11eb-81a8-d918064a960d.png">

**Comment by thdxr** [comment]
Fixed in v2
