### ISSUE TITLE
sst build: importing non-exist module does not fail the build

### ISSUE THREAD

**Issue by fwang** [serverless-stack/sst#662]
### Issues
Importing `@nosuchpath/blah` does not fail the build.

![image (6)](https://user-images.githubusercontent.com/83515/128647225-4bcb4aa3-c6d2-4cc6-930a-02684cc96149.png)

---
_Requested by_
- Sam Hulic and David Martin on Slack https://serverless-stack.slack.com/archives/C01JG3B20RY/p1628446989248100?thread_ts=1628444037.242300&cid=C01JG3B20RY

**Comment by fwang** [comment]
@thdxr This might be a TS related issue. Here is what I found.

### I first created a JS SST project, and added this Lambda function:
```js
import { Image } from "@asdf/models";

export async function main() {
  ...
}
```
`sst build` fails with error:
<img width="821" alt="Screen Shot 2021-08-30 at 2 44 07 AM" src="https://user-images.githubusercontent.com/83515/131296748-7e368dd5-08c4-473f-8919-eea739d337ae.png">

### I then created a TS SST project, and added this Lambda function:
```ts
import { Image } from "@asdf/models";

export async function main(): Promise<APIGatewayProxyResult> {
  ...
}
```
`sst build` does not fail. It only printed a lint error:
<img width="606" alt="Screen Shot 2021-08-30 at 2 45 50 AM" src="https://user-images.githubusercontent.com/83515/131297220-ae88985d-a364-4c41-b163-83d96f32c040.png">

Can you take a quick look at this?

**Comment by thdxr** [comment]
Fixed in v2
