### ISSUE TITLE
sst deploy: deploy previously built artifact instead of rebuilding

### ISSUE THREAD

**Issue by fwang** [serverless-stack/sst#779]
---
Requested by:
- [geekmidas and Aram in Slack](https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1630564083210600)
- Dan https://serverless-stack.slack.com/archives/C01JG3B20RY/p1634136813087200
- Ross https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1647967037466469
- Aleksandr https://serverless-stack.slack.com/archives/C01JG3B20RY/p1653736611074769
- Taufik https://github.com/serverless-stack/serverless-stack/issues/1674
- Kiran https://serverless-stack.slack.com/archives/C01HQQVC8TH/p1654067787943349

**Comment by Brian-Azizi** [comment]
Is there any documentation on how to do this?

**Comment by Brian-Azizi** [comment]
Thanks!
