### ISSUE TITLE
Allow Function configuration of bundle disabled when srcPath is at the app root

### ISSUE THREAD

**Issue by fwang** [serverless-stack/sst#78]
This configuration is currently **not supported** because we need to zip the app root for each handler. So after a Lambda's zip is generated, the next Lambda's zip will contain the previous Lambda's zip inside .build, and the previous Lambda's zip inside cdk.out.

One solution would be to cherry pick what to zip. For example, zip should only include the esbuid's output (ie. .js and .js.map files) from the .build folder.

Also need to clear all .build folders generated from Lambda functions that has srcPath.

**Comment by thdxr** [comment]
v2 doesn't need srcpath
